/*

	This code will perform kinematically-constrained mass analysis on experimental and simulated data from nuclear reactions where the recoil is unbound
	and decays into a 3-body final state through some intermediate state (Ex: A(a,b)B*, B*->C*+c, C*->d+e so B*->c+d+e in the final state, and C* is the
	intermediate state, which may or may not be an excited state).

	This code can take experimental data input in the form of the ROOT files generated by RMSRecon/etc/Rachel2Root.cxx
	which simply "ROOT"-ifies the txt files from Rachel Shaffer's sorts (see her thesis here: https://repository.lsu.edu/gradschool_dissertations/6662/)

	This code can also take simulated data output from SABREslicer.cxx located at SABREsim/det/SABREslicer.cxx. This takes SABREsim data and formats
	it in the same format as the Rachel2Root data. 


	NOTE: This code assumes that TMassTable is loaded into ROOT. This can be done by doing one of the following:

		i)		manually running '.L /path/to/masstable.cpp+' everytime you open root

													OR

		ii) 	creating/editing ~/rootlogon.C to include: 'gROOT->ProcessLine(".L /path/to/masstable.cpp+");'
				so that it runs this automatically for you. Find masstable.cpp and associated header and dat file here:
				https://github.com/zmp26/masstable

	Alternatively just remove the dependency and hardcode masses instead.

*/


#include <map>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <chrono>
#include "TFile.h"
#include "TH1D.h"
#include "TString.h"
#include "TDirectory.h"
#include "missmass_mult2.h"
#include "missmass_mult2.cpp"//including .cpp for simple root macro purposes
#include "permHistoMM_mult2.h"//" above "
#include "permHistoMM_mult2.cpp"//" above "