/*

	This code will perform invariant mass analysis on experimental and simulated data with SABRE multiplicity 3

	This code can take experimental data input in the form of the ROOT files generated by RMSRecon/etc/Rachel2Root.cxx
	which simply "ROOT"-ifies the txt files from Rachel Shaffer's sorts (see her thesis here: https://repository.lsu.edu/gradschool_dissertations/6662/)

	This code can also take simulated data output from SABREslicer.cxx located at SABREsim/det/SABREslicer.cxx. This takes SABREsim data and formats
	it in the same format as the Rachel2Root data. 


	NOTE: This code assumes that TMassTable is loaded into ROOT. This can be done by doing one of the following:

		i)		manually running '.L /path/to/masstable.cpp+' everytime you open root

													OR

		ii) 	creating/editing ~/rootlogon.C to include: 'gROOT->ProcessLine(".L /path/to/masstable.cpp+");'
				so that it runs this automatically for you. Find masstable.cpp and associated header and dat file here:
				https://github.com/zmp26/masstable

	Alternatively just remove the dependency and hardcode masses instead.

*/

#include <map>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <chrono>
#include "TFile.h"
#include "TH1D.h"
#include "TString.h"
#include "TDirectory.h"
#include "invmass_mult3.h"
#include "invmass_mult3.cpp"//including .cpp for simple root macro purposes
#include "permHisto_mult3.h"//" above "
#include "permHisto_mult3.cpp"//" above "

const double DEGRAD = M_PI / 180.;
const double RADDEG = 180. / M_PI;

void B10ha_8BeHypothesis_kin4mcComparison(const char* input_filename, int gate1index, std::pair<double,double> gate1minmax, int gate2index, std::pair<double,double> gate2minmax, int gate3index, std::pair<double,double> gate3minmax, bool updateRecoilEx = true, bool updateIntermediateEx = true){

	std::string s = input_filename;
	size_t last_dot = s.find_last_of(".");
	std::string stem = (last_dot == std::string::npos) ? s : s.substr(0, last_dot);

	std::string sabre_str = stem + "_SABREanalyzed8Be.root";
	std::string kin4mc_str = stem + "_kin4mcanalyzed8Be.root";

	const char* SABRE_output_filename = sabre_str.c_str();
	const char* kin4mc_output_filename = kin4mc_str.c_str();

	TMassTable fMassTable;
	fMassTable.Init("/home/zachpurcell/masstable/masstable.dat");

	Hypothesis4 b9_be8_hypothesis;
	b9_be8_hypothesis.name = "B10ha_8BeHypothesis";

	b9_be8_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
	b9_be8_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
	b9_be8_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
	b9_be8_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("B",9);
	b9_be8_hypothesis.mass_intermediate = fMassTable.GetNuclearMassMeV("Be",8);
	b9_be8_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("H",1);
	b9_be8_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("He",4);
	b9_be8_hypothesis.masses[2] = fMassTable.GetNuclearMassMeV("He",4);

	// b9_be8_hypothesis.recoilEx = recoilEx;
	// b9_be8_hypothesis.intermediateEx = intermediateEx;
	// b9_be8_hypothesis.intermediateExGate = intermediateExGate;

	TFile *infile = new TFile(input_filename, "READ");
	if(!infile || infile->IsZombie()){
		std::cerr << "Input file is bad: " << input_filename << std::endl;
		return;
	}

	TTree *intree = (TTree*)infile->Get("mult3");
	if(!intree){
		std::cerr << "Could not get TTree 'mult3' from " << input_filename << std::endl;
		return;
	}

	long numentries = intree->GetEntries();

	InvMass_Mult3 SABRE_analysis;
	SABRE_analysis.Init(SABRE_output_filename);
	SABRE_analysis.SetHypothesis(b9_be8_hypothesis);
	SABRE_analysis.SetGate1(gate1index);
	SABRE_analysis.SetGate1MinMax(gate1minmax);
	SABRE_analysis.SetGate2(gate2index);
	SABRE_analysis.SetGate2MinMax(gate2minmax);
	SABRE_analysis.SetGate3(gate3index);
	SABRE_analysis.SetGate3MinMax(gate3minmax);

	InvMass_Mult3 kin4mc_analysis;
	kin4mc_analysis.Init(kin4mc_output_filename);
	kin4mc_analysis.SetHypothesis(b9_be8_hypothesis);
	kin4mc_analysis.SetGate1(gate1index);
	kin4mc_analysis.SetGate1MinMax(gate1minmax);
	kin4mc_analysis.SetGate2(gate2index);
	kin4mc_analysis.SetGate2MinMax(gate2minmax);
	kin4mc_analysis.SetGate3(gate3index);
	kin4mc_analysis.SetGate3MinMax(gate3minmax);

	double kinmc_e[4], kinmc_theta[4], kinmc_phi[4];
	intree->SetBranchAddress("kin_e", kinmc_e);
	intree->SetBranchAddress("kin_theta", kinmc_theta);
	intree->SetBranchAddress("kin_phi", kinmc_phi);

	double Ex, SPSE;
	intree->SetBranchAddress("ExE", &Ex);
	intree->SetBranchAddress("SPSEnergy", &SPSE);

	double E[3], theta[3], phi[3];
	intree->SetBranchAddress("SabreRingEnergy_hit1", &E[0]);
	intree->SetBranchAddress("thetalab_hit1", &theta[0]);
	intree->SetBranchAddress("philab_hit1", &phi[0]);

	intree->SetBranchAddress("SabreRingEnergy_hit2", &E[1]);
	intree->SetBranchAddress("thetalab_hit2", &theta[1]);
	intree->SetBranchAddress("philab_hit2", &phi[1]);

	intree->SetBranchAddress("SabreRingEnergy_hit3", &E[2]);
	intree->SetBranchAddress("thetalab_hit3", &theta[2]);
	intree->SetBranchAddress("philab_hit3", &phi[2]);

	std::cout << "Starting analysis on " << numentries << " entries..." << std::endl;
	for(long i=0; i<numentries; i++){

		intree->GetEntry(i);

		double kinmc_bue[3], kinmc_butheta[3], kinmc_buphi[3];
		for(int j=0; j<3; j++){
			kinmc_bue[j] = kinmc_e[j+1];
			kinmc_butheta[j] = kinmc_theta[j+1];
			kinmc_buphi[j] = kinmc_phi[j+1];
		}

		//pass along SPS-informed recoil Ex if enabled:
		if(updateRecoilEx){
			SABRE_analysis.SetRecoilEx(Ex);
			//SABRE_analysis.SetExpectedCMValues();

			kin4mc_analysis.SetRecoilEx(Ex);
			//kin4mc_analysis.SetExpectedCMValues();
		}

		SABRE_analysis.AnalyzeEvent(E, theta, phi, updateIntermediateEx);
		SABRE_analysis.FillEventHistograms(Ex);
		int numpasses_sabre = SABRE_analysis.CountPermPasses();
		SABRE_analysis.FillPermCounter();
		SABRE_analysis.FillSortedHisto(Ex);
		if(numpasses_sabre == 2){
			SABRE_analysis.FillGatedEventHistograms(Ex); //due to symmetry of 8Be -> a + a, cases 012, 021 are identical, so check if 2 permutations pass intsead of just 1
			SABRE_analysis.FillPermCounter(true);
		}
		SABRE_analysis.FillTree();
		//SABRE_analysis.FillGatedEventHistograms(); 

		kin4mc_analysis.AnalyzeEvent(kinmc_bue, kinmc_butheta, kinmc_buphi, updateIntermediateEx);
		kin4mc_analysis.FillEventHistograms(Ex);
		int numpasses_kin4mc = kin4mc_analysis.CountPermPasses();
		kin4mc_analysis.FillPermCounter();
		kin4mc_analysis.FillSortedHisto(Ex);
		if(numpasses_kin4mc == 2){
			kin4mc_analysis.FillGatedEventHistograms(Ex); //due to symmetry of 8Be -> a + a, cases 012, 021 are identical, so check if 2 permutations pass intsead of just 1
			kin4mc_analysis.FillPermCounter(true);
		}
		kin4mc_analysis.FillTree();
		//kin4mc_analysis.FillGatedEventHistograms();

		if(i % 1000 == 0){
			fprintf(stdout, "\rProgress: %.1f%% (%ld/%ld)",(float)i/numentries*100., i, numentries);
			fflush(stdout);
		}

	}

	SABRE_analysis.CloseAndWrite();
	kin4mc_analysis.CloseAndWrite();
	infile->Close();

	std::cout << "\n\nAnalysis complete!\n" << std::endl;
	std::cout << "SABRE output:  " << SABRE_output_filename << std::endl;
	std::cout << "kin4mc output: " << kin4mc_output_filename << std::endl;

}

void B10ha_8BeHypothesis(const char* input_filename, int gate1index, std::pair<double,double> gate1minmax, int gate2index, std::pair<double,double> gate2minmax, int gate3index, std::pair<double,double> gate3minmax, bool updateRecoilEx = true, bool updateIntermediateEx = true, int permCheck = 2){

	std::string s = input_filename;
	size_t last_dot = s.find_last_of(".");
	std::string stem = (last_dot == std::string::npos) ? s : s.substr(0, last_dot);

	std::string sabre_str = stem + "_SABREanalyzed8Be.root";

	const char* SABRE_output_filename = sabre_str.c_str();

	TMassTable fMassTable;
	fMassTable.Init("/home/zachpurcell/masstable/masstable.dat");

	Hypothesis4 b9_be8_hypothesis;
	b9_be8_hypothesis.name = "B10ha_8BeHypothesis";

	b9_be8_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
	b9_be8_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
	b9_be8_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
	b9_be8_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("B",9);
	b9_be8_hypothesis.mass_intermediate = fMassTable.GetNuclearMassMeV("Be",8);
	b9_be8_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("H",1);
	b9_be8_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("He",4);
	b9_be8_hypothesis.masses[2] = fMassTable.GetNuclearMassMeV("He",4);

	TFile *infile = new TFile(input_filename, "READ");
	if(!infile || infile->IsZombie()){
		std::cerr << "Input file is bad: " << input_filename << std::endl;
		return;
	}

	TTree *intree = (TTree*)infile->Get("mult3");
	if(!intree){
		std::cerr << "Could not get TTree 'mult3' from " << input_filename << std::endl;
		return;
	}

	long numentries = intree->GetEntries();

	InvMass_Mult3 SABRE_analysis;;
	SABRE_analysis.Init(SABRE_output_filename);
	SABRE_analysis.SetHypothesis(b9_be8_hypothesis);
	SABRE_analysis.SetGate1(gate1index);
	SABRE_analysis.SetGate1MinMax(gate1minmax);
	SABRE_analysis.SetGate2(gate2index);
	SABRE_analysis.SetGate2MinMax(gate2minmax);
	SABRE_analysis.SetGate3(gate3index);
	SABRE_analysis.SetGate3MinMax(gate3minmax);

	double Ex, SPSE;
	intree->SetBranchAddress("ExE", &Ex);
	intree->SetBranchAddress("SPSEnergy", &SPSE);

	double E[3], theta[3], phi[3];
	intree->SetBranchAddress("SabreRingEnergy_hit1", &E[0]);
	intree->SetBranchAddress("thetalab_hit1", &theta[0]);
	intree->SetBranchAddress("philab_hit1", &phi[0]);

	intree->SetBranchAddress("SabreRingEnergy_hit2", &E[1]);
	intree->SetBranchAddress("thetalab_hit2", &theta[1]);
	intree->SetBranchAddress("philab_hit2", &phi[1]);

	intree->SetBranchAddress("SabreRingEnergy_hit3", &E[2]);
	intree->SetBranchAddress("thetalab_hit3", &theta[2]);
	intree->SetBranchAddress("philab_hit3", &phi[2]);

	std::cout << "Starting analysis on " << numentries << " entries..." << std::endl;
	for(long i=0; i<numentries; i++){

		intree->GetEntry(i);

		//pass along SPS-informed recoil Ex if enabled:
		if(updateRecoilEx){
			SABRE_analysis.SetRecoilEx(Ex);
		}

		SABRE_analysis.AnalyzeEvent(E, theta, phi, updateIntermediateEx);
		SABRE_analysis.FillEventHistograms(Ex);
		int numpasses_sabre = SABRE_analysis.CountPermPasses();
		SABRE_analysis.FillPermCounter();
		SABRE_analysis.FillSortedHisto(Ex);
		if(numpasses_sabre == permCheck){ 
			SABRE_analysis.FillGatedEventHistograms(Ex); //due to symmetry of 8Be -> a + a, cases 012, 021 are identical, so check if 2 permutations pass intsead of just 1
			SABRE_analysis.FillPermCounter(true);
		}
		SABRE_analysis.FillTree();

		if(i % 1000 == 0){
			fprintf(stdout, "\rProgress: %.1f%% (%ld/%ld)",(float)i/numentries*100., i, numentries);
			fflush(stdout);
		}

	}

	SABRE_analysis.CloseAndWrite();

	infile->Close();

	std::cout << "\n\nAnalysis complete!\n" << std::endl;
	std::cout << "SABRE output:  " << SABRE_output_filename << std::endl;
}

void tempDoAll_8BeHypothesis(int gate1index, int gate2index, int gate3index, int permCheck = 2, bool updateRecoilEx = true, bool updateIntermediateEx = true){

	// std::vector<int> intExs = {0, 250, 500, 750, 1000, 1250};
	// std::vector<std::pair<double,double>> intEminmax = {{-0.05, 0.1}, {-0.05, 0.1}, {-0.05, 0.1}, {-0.05, 0.1}, {-0.05, 0.1}, {-0.05, 0.1}};//MeV
	// std::vector<std::pair<double,double>> intVCMminmax = {{0.0017, 0.00295}, {0.00289, 0.00429}, {0.00382, 0.00503}, {0.00461, 0.00575}, {0.00527, 0.00637}, {0.00593, 0.00695}};//c
	// std::vector<std::pair<double,double>> frag1VCMminmax = {{0.01355, 0.02275}, {0.024, 0.03321}, {0.03051, 0.03985}, {0.03667, 0.04527}, {0.04274, 0.05045}, {0.04797, 0.0549}};//c

	std::vector<int> intExs = {0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500};
	std::vector<std::pair<double,double>> intEminmax = {{-0.05, 0.1}, {-0.05, 0.1}, {-0.05, 0.1}, {-0.05, 0.1}, {-0.05, 0.1}, {-0.05, 0.1}, {-0.05, 0.1}, {-0.05, 0.1}, {-0.05, 0.1}, {-0.05, 0.1}, {-0.05, 0.1}};
	std::vector<std::pair<double,double>> intVCMminmax = {{0.0017, 0.00295}, {0.00193, 0.0031}, {0.00219, 0.00363}, {0.00245, 0.00389}, {0.00267, 0.00412}, {0.00289, 0.00429}, {0.00301, 0.00451}, {0.00321, 0.00471}, {0.00333, 0.00485}, {0.00347, 0.00501}, {0.00382, 0.00503}};
	std::vector<std::pair<double,double>> frag1VCMminmax = {{0.01355, 0.02275}, {0.01537, 0.02595}, {0.01791, 0.02817}, {0.01967, 0.3035}, {0.02159, 0.03199}, {0.024, 0.03321}, {0.02493, 0.03541}, {0.02599, 0.03665}, {0.02752, 0.03769}, {0.02854, 0.03911}, {0.03051, 0.03985}};

 	std::pair<double,double> minmax1, minmax2, minmax3;

 	for(size_t i=0; i<intExs.size(); i++){
 		int intEx = intExs.at(i);
 		TString filename = Form("may16/det/b10ha_7.5MeV_9B_ex%dkeV_p8Be_ex0keV_1000k_tree_mult3.root", intEx);
 	
 		switch(gate1index){
			case NOCHECK:
				minmax1 = {0.,0.};
				break;
			case INTEXCHECK:
				minmax1 = intEminmax.at(i);
				break;
			case INTVCMCHECK:
				minmax1 = intVCMminmax.at(i);
				break;
			case FRAG1VCMCHECK:
				minmax1 = frag1VCMminmax.at(i);
				break;
			default:
				minmax1 = {0., 0.};
				break;
		}

		switch(gate2index){
			case NOCHECK:
				minmax2 = {0.,0.};
				break;
			case INTEXCHECK:
				minmax2 = intEminmax.at(i);
				break;
			case INTVCMCHECK:
				minmax2 = intVCMminmax.at(i);
				break;
			case FRAG1VCMCHECK:
				minmax2 = frag1VCMminmax.at(i);
				break;
			default:
				minmax2 = {0., 0.};
				break;
		}

		switch(gate3index){
			case NOCHECK:
				minmax3 = {0.,0.};
				break;
			case INTEXCHECK:
				minmax3 = intEminmax.at(i);
				break;
			case INTVCMCHECK:
				minmax3 = intVCMminmax.at(i);
				break;
			case FRAG1VCMCHECK:
				minmax3 = frag1VCMminmax.at(i);
				break;
			default:
				minmax3 = {0., 0.};
				break;
		}

		B10ha_8BeHypothesis(filename.Data(), gate1index, minmax1, gate2index, minmax2, gate3index, minmax3, updateRecoilEx, updateIntermediateEx, permCheck);

		std::cout << "Generated " << filename.Data() << std::endl << std::endl;

 	}

}

void B10ha_5LiHypothesis_kin4mcComparison(const char* input_filename, int gate1index, std::pair<double,double> gate1minmax, int gate2index, std::pair<double,double> gate2minmax, int gate3index, std::pair<double,double> gate3minmax, bool updateRecoilEx = false, bool updateIntermediateEx = false){

	std::string s = input_filename;
	size_t last_dot = s.find_last_of(".");
	std::string stem = (last_dot == std::string::npos) ? s : s.substr(0, last_dot);

	std::string sabre_str = stem + "_SABREanalyzed5Li.root";
	std::string kin4mc_str = stem + "_kin4mcanalyzed5Li.root";

	const char* SABRE_output_filename = sabre_str.c_str();
	const char* kin4mc_output_filename = kin4mc_str.c_str();

	TMassTable fMassTable;
	fMassTable.Init("/home/zachpurcell/masstable/masstable.dat");

	Hypothesis4 b9_li5_hypothesis;
	b9_li5_hypothesis.name = "B10ha_5LiHypothesis";

	b9_li5_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
	b9_li5_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
	b9_li5_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
	b9_li5_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("B",9);
	b9_li5_hypothesis.mass_intermediate = fMassTable.GetNuclearMassMeV("Li",5);
	b9_li5_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("He",4);
	b9_li5_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("H",1);
	b9_li5_hypothesis.masses[2] = fMassTable.GetNuclearMassMeV("He",4);

	TFile *infile = new TFile(input_filename, "READ");
	if(!infile || infile->IsZombie()){
		std::cerr << "Input file is bad: " << input_filename << std::endl;
		return;
	}

	TTree *intree = (TTree*)infile->Get("mult3");
	if(!intree){
		std::cerr << "Could not get TTree 'mult3' from " << input_filename << std::endl;
		return;
	}

	long numentries = intree->GetEntries();

	InvMass_Mult3 SABRE_analysis;;
	SABRE_analysis.Init(SABRE_output_filename);
	SABRE_analysis.SetHypothesis(b9_li5_hypothesis);
	SABRE_analysis.SetGate1(gate1index);
	SABRE_analysis.SetGate1MinMax(gate1minmax);
	SABRE_analysis.SetGate2(gate2index);
	SABRE_analysis.SetGate2MinMax(gate2minmax);
	SABRE_analysis.SetGate3(gate3index);
	SABRE_analysis.SetGate3MinMax(gate3minmax);

	InvMass_Mult3 kin4mc_analysis;
	kin4mc_analysis.Init(kin4mc_output_filename);
	kin4mc_analysis.SetHypothesis(b9_li5_hypothesis);
	kin4mc_analysis.SetGate1(gate1index);
	kin4mc_analysis.SetGate1MinMax(gate1minmax);
	kin4mc_analysis.SetGate2(gate2index);
	kin4mc_analysis.SetGate2MinMax(gate2minmax);
	kin4mc_analysis.SetGate3(gate3index);
	kin4mc_analysis.SetGate3MinMax(gate3minmax);

	double kinmc_e[4], kinmc_theta[4], kinmc_phi[4];
	intree->SetBranchAddress("kin_e", kinmc_e);
	intree->SetBranchAddress("kin_theta", kinmc_theta);
	intree->SetBranchAddress("kin_phi", kinmc_phi);

	double Ex, SPSE;
	intree->SetBranchAddress("ExE", &Ex);
	intree->SetBranchAddress("SPSEnergy", &SPSE);

	double E[3], theta[3], phi[3];
	intree->SetBranchAddress("SabreRingEnergy_hit1", &E[0]);
	intree->SetBranchAddress("thetalab_hit1", &theta[0]);
	intree->SetBranchAddress("philab_hit1", &phi[0]);

	intree->SetBranchAddress("SabreRingEnergy_hit2", &E[1]);
	intree->SetBranchAddress("thetalab_hit2", &theta[1]);
	intree->SetBranchAddress("philab_hit2", &phi[1]);

	intree->SetBranchAddress("SabreRingEnergy_hit3", &E[2]);
	intree->SetBranchAddress("thetalab_hit3", &theta[2]);
	intree->SetBranchAddress("philab_hit3", &phi[2]);

	std::cout << "Starting analysis on " << numentries << " entries..." << std::endl;

	for(long i=0; i<numentries; i++){

		intree->GetEntry(i);

		double kinmc_bue[3], kinmc_butheta[3], kinmc_buphi[3];
		for(int j=0; j<3; j++){
			kinmc_bue[j] = kinmc_e[j+1];
			kinmc_butheta[j] = kinmc_theta[j+1];
			kinmc_buphi[j] = kinmc_phi[j+1];
		}

		//pass along SPS-informed recoil Ex if enabled:
		if(updateRecoilEx){
			SABRE_analysis.SetRecoilEx(Ex);
			//SABRE_analysis.SetExpectedCMValues();

			kin4mc_analysis.SetRecoilEx(Ex);
			//kin4mc_analysis.SetExpectedCMValues();
		}

		SABRE_analysis.AnalyzeEvent(E, theta, phi, updateIntermediateEx);
		SABRE_analysis.FillEventHistograms(Ex);
		int numpasses_sabre = SABRE_analysis.CountPermPasses();
		SABRE_analysis.FillPermCounter();
		SABRE_analysis.FillSortedHisto(Ex);
		if(numpasses_sabre == 1){
			SABRE_analysis.FillGatedEventHistograms(Ex);
			SABRE_analysis.FillPermCounter(true);
		}
		SABRE_analysis.FillTree();

		kin4mc_analysis.AnalyzeEvent(kinmc_bue, kinmc_butheta, kinmc_buphi, updateIntermediateEx);
		kin4mc_analysis.FillEventHistograms(Ex);
		int numpasses_kin4mc = kin4mc_analysis.CountPermPasses();
		kin4mc_analysis.FillPermCounter();
		kin4mc_analysis.FillSortedHisto(Ex);
		if(numpasses_kin4mc == 1){
			kin4mc_analysis.FillGatedEventHistograms(Ex);
			kin4mc_analysis.FillPermCounter(true);
		}
		kin4mc_analysis.FillTree();

		if(i % 1000 == 0){
			fprintf(stdout, "\rProgress: %.1f%% (%ld/%ld)",(float)i/numentries*100., i, numentries);
			fflush(stdout);
		}

	}

	SABRE_analysis.CloseAndWrite();
	kin4mc_analysis.CloseAndWrite();
	infile->Close();

	std::cout << "\n\nAnalysis complete!\n" << std::endl;
	std::cout << "SABRE output:  " << SABRE_output_filename << std::endl;
	std::cout << "kin4mc output: " << kin4mc_output_filename << std::endl;

}

void B10ha_5LiHypothesis(const char* input_filename, int gate1index, std::pair<double,double> gate1minmax, int gate2index, std::pair<double,double> gate2minmax, int gate3index, std::pair<double,double> gate3minmax, bool updateRecoilEx = false, bool updateIntermediateEx = false){

	std::string s = input_filename;
	size_t last_dot = s.find_last_of(".");
	std::string stem = (last_dot == std::string::npos) ? s : s.substr(0, last_dot);

	std::string sabre_str = stem + "_SABREanalyzed5Li.root";
	std::string kin4mc_str = stem + "_kin4mcanalyzed5Li.root";

	const char* SABRE_output_filename = sabre_str.c_str();
	const char* kin4mc_output_filename = kin4mc_str.c_str();

	TMassTable fMassTable;
	fMassTable.Init("/home/zachpurcell/masstable/masstable.dat");

	Hypothesis4 b9_li5_hypothesis;
	b9_li5_hypothesis.name = "B10ha_5LiHypothesis";

	b9_li5_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
	b9_li5_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
	b9_li5_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
	b9_li5_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("B",9);
	b9_li5_hypothesis.mass_intermediate = fMassTable.GetNuclearMassMeV("Li",5);
	b9_li5_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("He",4);
	b9_li5_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("H",1);
	b9_li5_hypothesis.masses[2] = fMassTable.GetNuclearMassMeV("He",4);

	TFile *infile = new TFile(input_filename, "READ");
	if(!infile || infile->IsZombie()){
		std::cerr << "Input file is bad: " << input_filename << std::endl;
		return;
	}

	TTree *intree = (TTree*)infile->Get("mult3");
	if(!intree){
		std::cerr << "Could not get TTree 'mult3' from " << input_filename << std::endl;
		return;
	}

	long numentries = intree->GetEntries();

	InvMass_Mult3 SABRE_analysis;;
	SABRE_analysis.Init(SABRE_output_filename);
	SABRE_analysis.SetHypothesis(b9_li5_hypothesis);
	SABRE_analysis.SetGate1(gate1index);
	SABRE_analysis.SetGate1MinMax(gate1minmax);
	SABRE_analysis.SetGate2(gate2index);
	SABRE_analysis.SetGate2MinMax(gate2minmax);
	SABRE_analysis.SetGate3(gate3index);
	SABRE_analysis.SetGate3MinMax(gate3minmax);

	double Ex, SPSE;
	intree->SetBranchAddress("ExE", &Ex);
	intree->SetBranchAddress("SPSEnergy", &SPSE);

	double E[3], theta[3], phi[3];
	intree->SetBranchAddress("SabreRingEnergy_hit1", &E[0]);
	intree->SetBranchAddress("thetalab_hit1", &theta[0]);
	intree->SetBranchAddress("philab_hit1", &phi[0]);

	intree->SetBranchAddress("SabreRingEnergy_hit2", &E[1]);
	intree->SetBranchAddress("thetalab_hit2", &theta[1]);
	intree->SetBranchAddress("philab_hit2", &phi[1]);

	intree->SetBranchAddress("SabreRingEnergy_hit3", &E[2]);
	intree->SetBranchAddress("thetalab_hit3", &theta[2]);
	intree->SetBranchAddress("philab_hit3", &phi[2]);

	std::cout << "Starting analysis on " << numentries << " entries..." << std::endl;

	for(long i=0; i<numentries; i++){

		intree->GetEntry(i);

		//pass along SPS-informed recoil Ex if enabled:
		if(updateRecoilEx){
			SABRE_analysis.SetRecoilEx(Ex);
		}

		SABRE_analysis.AnalyzeEvent(E, theta, phi, updateIntermediateEx);
		SABRE_analysis.FillEventHistograms(Ex);
		int numpasses_sabre = SABRE_analysis.CountPermPasses();
		SABRE_analysis.FillPermCounter();
		SABRE_analysis.FillSortedHisto(Ex);
		if(numpasses_sabre == 1){
			SABRE_analysis.FillGatedEventHistograms(Ex);
			SABRE_analysis.FillPermCounter(true);
		}
		SABRE_analysis.FillTree();

		if(i % 1000 == 0){
			fprintf(stdout, "\rProgress: %.1f%% (%ld/%ld)",(float)i/numentries*100., i, numentries);
			fflush(stdout);
		}

	}

	SABRE_analysis.CloseAndWrite();
	infile->Close();

	std::cout << "\n\nAnalysis complete!\n" << std::endl;
	std::cout << "SABRE output:  " << SABRE_output_filename << std::endl;

}

void tempDoAll_5LiHypothesis(int gate1index, int gate2index, int gate3index, bool updateRecoilEx = false, bool updateIntermediateEx = false){

	std::vector<int> intExs;
	std::vector<std::pair<double,double>> intEminmax;
	std::vector<std::pair<double,double>> intVCMminmax;
	std::vector<std::pair<double,double>> frag1VCMminmax;

	//update above values for 5Li case (just copied from 8Be)
	std::pair<double,double> minmax1, minmax2, minmax3;

	//for(auto const &intEx : intExs){
	for(size_t i=0; i<intExs.size(); i++){
		int intEx = intExs.at(i);
		TString filename = Form("may16/det/b10ha_7.5MeV_9B_ex%dkeV_a5Li_ex0keV_1000k_tree_mult3.root", intEx);

		switch(gate1index){
			case NOCHECK:
				minmax1 = {0.,0.};
				break;
			case INTEXCHECK:
				minmax1 = intEminmax.at(i);
				break;
			case INTVCMCHECK:
				minmax1 = intVCMminmax.at(i);
				break;
			case FRAG1VCMCHECK:
				minmax1 = frag1VCMminmax.at(i);
				break;
			default:
				minmax1 = {0., 0.};
				break;
		}

		switch(gate2index){
			case NOCHECK:
				minmax2 = {0.,0.};
				break;
			case INTEXCHECK:
				minmax2 = intEminmax.at(i);
				break;
			case INTVCMCHECK:
				minmax2 = intVCMminmax.at(i);
				break;
			case FRAG1VCMCHECK:
				minmax2 = frag1VCMminmax.at(i);
				break;
			default:
				minmax2 = {0., 0.};
				break;
		}

		switch(gate3index){
			case NOCHECK:
				minmax3 = {0.,0.};
				break;
			case INTEXCHECK:
				minmax3 = intEminmax.at(i);
				break;
			case INTVCMCHECK:
				minmax3 = intVCMminmax.at(i);
				break;
			case FRAG1VCMCHECK:
				minmax3 = frag1VCMminmax.at(i);
				break;
			default:
				minmax3 = {0., 0.};
				break;
		}

		B10ha_5LiHypothesis(filename.Data(), gate1index, minmax1, gate2index, minmax2, gate3index, minmax3, updateRecoilEx, updateIntermediateEx);
	}
}


void tempDoAll_BothHypothesis(){

	auto totalStart = std::chrono::steady_clock::now();

	std::vector<TString> hypotheses = {"p8Be", "a5Li"};
	std::vector<int> states = {2345, 2751, 2780};
	//int total = (int)(hypotheses.size() * states.size());
	int total = (int)(states.size());

	int count = 0;

	for(auto const &state : states){
		for(auto const &hyp : hypotheses){
			auto localStart = std::chrono::steady_clock::now();
			TString filename = Form("/mnt/e/SABREsim/analyze/may22/det/b10ha_7.5MeV_9B_ex%dkeV_%s_ex0keV_1mil_tree_mult3.root", state, hyp.Data());
			B10ha_8BeHypothesis(filename.Data(), NOCHECK, {0,0}, NOCHECK, {0,0}, NOCHECK, {0,0});
			B10ha_5LiHypothesis(filename.Data(), NOCHECK, {0,0}, NOCHECK, {0,0}, NOCHECK, {0,0});
			count++;
			auto localStop = std::chrono::steady_clock::now();
			auto localElapsed = std::chrono::duration_cast<std::chrono::seconds>(localStop-localStart);
			std::cout << "Finished " << count << " out of " << total << " (" << count*100./total << "%)\t(" << localElapsed.count() << "s)\n\n" << std::endl;
		}
		
	}

	// for(auto const &state : states){
	// 	auto localStart = std::chrono::steady_clock::now();
	// 	TString filename = Form("/mnt/e/SABREsim/analyze/may22/det/b10ha_7.5MeV_9B_ex%dkeV_tree_mult3.root",state);
	// 	//std::cout << "here..." << std::endl;
	// 	B10ha_8BeHypothesis(filename.Data(), NOCHECK, {0,0}, NOCHECK, {0,0}, NOCHECK, {0,0});
	// 	//std::cout << "and here..." << std::endl;
	// 	B10ha_5LiHypothesis(filename.Data(), NOCHECK, {0,0}, NOCHECK, {0,0}, NOCHECK, {0,0});
	// 	//std::cout << "here too..." << std::endl;
	// 	count++;
	// 	auto localStop = std::chrono::steady_clock::now();
	// 	auto localElapsed = std::chrono::duration_cast<std::chrono::seconds>(localStop-localStart);
	// 	std::cout << "Finished " << count << " out of " << total << " (" << count*100./total << "%)\t(" << localElapsed.count() << "s)\n\n" << std::endl;
	// }

	auto end = std::chrono::steady_clock::now();
	auto elapsed = std::chrono::duration_cast<std::chrono::seconds>(end - totalStart);

	std::cout << "\n\nFinished all analysis! Elapsed time: " << elapsed.count() << " seconds\n\n"<< std::endl;
}


//------------------------------DATA BELOW-------------------------------------
void B10ha_3par_exp_aboveAlphaThresh(const char* input_filename, bool updateRecoilEx = true, bool updateIntermediateEx = true){

	std::string s = input_filename;
	size_t last_dot = s.find_last_of(".");
	std::string stem = (last_dot == std::string::npos) ? s : s.substr(0, last_dot);

	std::string p8Be_str = stem + "_aboveAlphaThreshAnalyzed8Be.root";
	std::string a5Li_str = stem + "_aboveAlphaThreshAnalyzed5Li.root";

	const char* p8Be_output_filename = p8Be_str.c_str();
	const char* a5Li_output_filename = a5Li_str.c_str();

	TFile *infile = new TFile(input_filename, "READ");
	if(!infile || infile->IsZombie()){
		std::cerr << "Input file is bad: " << input_filename << std::endl;
		return;
	}

	TTree *intree = (TTree*)infile->Get("mult3");
	if(!intree){
		std::cerr << "Could not get TTree 'mult3' from " << input_filename << std::endl;
		return;
	}

	long numentries = intree->GetEntries();

	TMassTable fMassTable;
	fMassTable.Init("/home/zachpurcell/masstable/masstable.dat");

	Hypothesis4 b9_p8Be_hypothesis, b9_a5Li_hypothesis;

	b9_p8Be_hypothesis.name = "B10ha_8BeHypothesis";
	b9_p8Be_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
	b9_p8Be_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
	b9_p8Be_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
	b9_p8Be_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("B",9);
	b9_p8Be_hypothesis.mass_intermediate = fMassTable.GetNuclearMassMeV("Be",8);
	b9_p8Be_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("H",1);
	b9_p8Be_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("He",4);
	b9_p8Be_hypothesis.masses[2] = fMassTable.GetNuclearMassMeV("He",4);


	b9_a5Li_hypothesis.name = "B10ha_5LiHypothesis";
	b9_a5Li_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
	b9_a5Li_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
	b9_a5Li_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
	b9_a5Li_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("B",9);
	b9_a5Li_hypothesis.mass_intermediate = fMassTable.GetNuclearMassMeV("Li",5);
	b9_a5Li_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("He",4);
	b9_a5Li_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("H",1);
	b9_a5Li_hypothesis.masses[2] = fMassTable.GetNuclearMassMeV("He",4);


	InvMass_Mult3 b9_p8Be_analysis, b9_a5Li_analysis;

	b9_p8Be_analysis.Init(p8Be_output_filename);
	b9_p8Be_analysis.SetHypothesis(b9_p8Be_hypothesis);
	b9_p8Be_analysis.SetGate1(NOCHECK);
	b9_p8Be_analysis.SetGate1MinMax({0,0});
	b9_p8Be_analysis.SetGate2(NOCHECK);
	b9_p8Be_analysis.SetGate2MinMax({0,0});
	b9_p8Be_analysis.SetGate3(NOCHECK);
	b9_p8Be_analysis.SetGate3MinMax({0,0});

	b9_a5Li_analysis.Init(a5Li_output_filename);
	b9_a5Li_analysis.SetHypothesis(b9_a5Li_hypothesis);
	b9_a5Li_analysis.SetGate1(NOCHECK);
	b9_a5Li_analysis.SetGate1MinMax({0,0});
	b9_a5Li_analysis.SetGate2(NOCHECK);
	b9_a5Li_analysis.SetGate2MinMax({0,0});
	b9_a5Li_analysis.SetGate3(NOCHECK);
	b9_a5Li_analysis.SetGate3MinMax({0,0});


	double Ex, SPSE;
	intree->SetBranchAddress("ExE", &Ex);
	intree->SetBranchAddress("SPSEnergy", &SPSE);

	double E[3], theta[3], phi[3];
	intree->SetBranchAddress("SabreRingEnergy_hit1", &E[0]);
	intree->SetBranchAddress("thetalab_hit1", &theta[0]);
	intree->SetBranchAddress("philab_hit1", &phi[0]);

	intree->SetBranchAddress("SabreRingEnergy_hit2", &E[1]);
	intree->SetBranchAddress("thetalab_hit2", &theta[1]);
	intree->SetBranchAddress("philab_hit2", &phi[1]);

	intree->SetBranchAddress("SabreRingEnergy_hit3", &E[2]);
	intree->SetBranchAddress("thetalab_hit3", &theta[2]);
	intree->SetBranchAddress("philab_hit3", &phi[2]);

	std::cout << "Starting analysis on " << numentries << " entries..." << std::endl;
	for(long i=0; i<numentries; i++){

		intree->GetEntry(i);

		if(updateRecoilEx){
			b9_p8Be_analysis.SetRecoilEx(Ex);
			b9_a5Li_analysis.SetRecoilEx(Ex);
		}

	if(Ex >= 1.7){//only look at events we suspect are energetically capable of decaying via p+8Be OR a+5Li
		b9_p8Be_analysis.AnalyzeEvent(E, theta, phi, updateIntermediateEx);
		b9_p8Be_analysis.FillEventHistograms(Ex);
		int numpasses_p8Be = b9_p8Be_analysis.CountPermPasses();
		b9_p8Be_analysis.FillPermCounter();
		b9_p8Be_analysis.FillSortedHisto(Ex);
		b9_p8Be_analysis.FillTree();

		b9_a5Li_analysis.AnalyzeEvent(E, theta, phi, updateIntermediateEx);
		b9_a5Li_analysis.FillEventHistograms(Ex);
		int numpasses_a5Li = b9_a5Li_analysis.CountPermPasses();
		b9_a5Li_analysis.FillPermCounter();
		b9_a5Li_analysis.FillSortedHisto(Ex);
		b9_a5Li_analysis.FillTree();
	}

		if(i % 1000 == 0){
			fprintf(stdout, "\rProgress: %.1f%% (%ld/%ld)",(float)i/numentries*100., i, numentries);
			fflush(stdout);
		}

	}

	b9_p8Be_analysis.CloseAndWrite();
	b9_a5Li_analysis.CloseAndWrite();

	infile->Close();

	std::cout << "\n\nAnalysis complete!\n" << std::endl;
	std::cout << "b9_p8Be output: " << p8Be_output_filename << std::endl;
	std::cout << "b9_a5Li output: " << a5Li_output_filename << std::endl;
}

void B10ha_3par_exp_allEx(const char* input_filename, bool updateRecoilEx = true, bool updateIntermediateEx = true){

	std::string s = input_filename;
	size_t last_dot = s.find_last_of(".");
	std::string stem = (last_dot == std::string::npos) ? s : s.substr(0, last_dot);

	std::string p8Be_str = stem + "_allExAnalyzed8Be.root";
	// std::string a5Li_str = stem + "_analyzed5Li.root";

	const char* p8Be_output_filename = p8Be_str.c_str();
	//const char* a5Li_output_filename = a5Li_str.c_str();

	TFile *infile = new TFile(input_filename, "READ");
	if(!infile || infile->IsZombie()){
		std::cerr << "Input file is bad: " << input_filename << std::endl;
		return;
	}

	TTree *intree = (TTree*)infile->Get("mult3");
	if(!intree){
		std::cerr << "Could not get TTree 'mult3' from " << input_filename << std::endl;
		return;
	}

	long numentries = intree->GetEntries();

	TMassTable fMassTable;
	fMassTable.Init("/home/zachpurcell/masstable/masstable.dat");

	Hypothesis4 b9_p8Be_hypothesis;//, b9_a5Li_hypothesis;

	b9_p8Be_hypothesis.name = "B10ha_8BeHypothesis";
	b9_p8Be_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
	b9_p8Be_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
	b9_p8Be_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
	b9_p8Be_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("B",9);
	b9_p8Be_hypothesis.mass_intermediate = fMassTable.GetNuclearMassMeV("Be",8);
	b9_p8Be_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("H",1);
	b9_p8Be_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("He",4);
	b9_p8Be_hypothesis.masses[2] = fMassTable.GetNuclearMassMeV("He",4);


	// b9_a5Li_hypothesis.name = "B10ha_5LiHypothesis";
	// b9_a5Li_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
	// b9_a5Li_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
	// b9_a5Li_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
	// b9_a5Li_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("B",9);
	// b9_a5Li_hypothesis.mass_intermediate = fMassTable.GetNuclearMassMeV("Li",5);
	// b9_a5Li_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("He",4);
	// b9_a5Li_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("H",1);
	// b9_a5Li_hypothesis.masses[2] = fMassTable.GetNuclearMassMeV("He",4);


	InvMass_Mult3 b9_p8Be_analysis;//, b9_a5Li_analysis;

	b9_p8Be_analysis.Init(p8Be_output_filename);
	b9_p8Be_analysis.SetHypothesis(b9_p8Be_hypothesis);
	b9_p8Be_analysis.SetGate1(NOCHECK);
	b9_p8Be_analysis.SetGate1MinMax({0,0});
	b9_p8Be_analysis.SetGate2(NOCHECK);
	b9_p8Be_analysis.SetGate2MinMax({0,0});
	b9_p8Be_analysis.SetGate3(NOCHECK);
	b9_p8Be_analysis.SetGate3MinMax({0,0});

	// b9_a5Li_analysis.Init(a5Li_output_filename);
	// b9_a5Li_analysis.SetHypothesis(b9_a5Li_hypothesis);
	// b9_a5Li_analysis.SetGate1(NOCHECK);
	// b9_a5Li_analysis.SetGate1MinMax({0,0});
	// b9_a5Li_analysis.SetGate2(NOCHECK);
	// b9_a5Li_analysis.SetGate2MinMax({0,0});
	// b9_a5Li_analysis.SetGate3(NOCHECK);
	// b9_a5Li_analysis.SetGate3MinMax({0,0});


	double Ex, SPSE;
	intree->SetBranchAddress("ExE", &Ex);
	intree->SetBranchAddress("SPSEnergy", &SPSE);

	double E[3], theta[3], phi[3];
	intree->SetBranchAddress("SabreRingEnergy_hit1", &E[0]);
	intree->SetBranchAddress("thetalab_hit1", &theta[0]);
	intree->SetBranchAddress("philab_hit1", &phi[0]);

	intree->SetBranchAddress("SabreRingEnergy_hit2", &E[1]);
	intree->SetBranchAddress("thetalab_hit2", &theta[1]);
	intree->SetBranchAddress("philab_hit2", &phi[1]);

	intree->SetBranchAddress("SabreRingEnergy_hit3", &E[2]);
	intree->SetBranchAddress("thetalab_hit3", &theta[2]);
	intree->SetBranchAddress("philab_hit3", &phi[2]);

	std::cout << "Starting analysis on " << numentries << " entries..." << std::endl;
	for(long i=0; i<numentries; i++){

		intree->GetEntry(i);

		if(updateRecoilEx){
			b9_p8Be_analysis.SetRecoilEx(Ex);
			//b9_a5Li_analysis.SetRecoilEx(Ex);
		}


		b9_p8Be_analysis.AnalyzeEvent(E, theta, phi, updateIntermediateEx);
		b9_p8Be_analysis.FillEventHistograms(Ex);
		int numpasses_p8Be = b9_p8Be_analysis.CountPermPasses();
		b9_p8Be_analysis.FillPermCounter();
		b9_p8Be_analysis.FillSortedHisto(Ex);
		b9_p8Be_analysis.FillTree();

		// b9_a5Li_analysis.AnalyzeEvent(E, theta, phi, updateIntermediateEx);
		// b9_a5Li_analysis.FillEventHistograms(Ex);
		// int numpasses_a5Li = b9_a5Li_analysis.CountPermPasses();
		// b9_a5Li_analysis.FillPermCounter();


		if(i % 1000 == 0){
			fprintf(stdout, "\rProgress: %.1f%% (%ld/%ld)",(float)i/numentries*100., i, numentries);
			fflush(stdout);
		}

	}

	b9_p8Be_analysis.CloseAndWrite();
	//b9_a5Li_analysis.CloseAndWrite();

	infile->Close();

	std::cout << "\n\nAnalysis complete!\n" << std::endl;
	std::cout << "b9_p8Be output: " << p8Be_output_filename << std::endl;
	//std::cout << "b9_a5Li output: " << a5Li_output_filename << std::endl;
}
