/*

	This code will perform invariant mass analysis on experimental and simulated data with SABRE multiplicity 3

	This code can take experimental data input in the form of the ROOT files generated by RMSRecon/etc/Rachel2Root.cxx
	which simply "ROOT"-ifies the txt files from Rachel Shaffer's sorts (see her thesis here: https://repository.lsu.edu/gradschool_dissertations/6662/)

	This code can also take simulated data output from SABREslicer.cxx located at SABREsim/det/SABREslicer.cxx. This takes SABREsim data and formats
	it in the same format as the Rachel2Root data. 


	NOTE: This code assumes that TMassTable is loaded into ROOT. This can be done by doing one of the following:

		i)		manually running '.L /path/to/masstable.cpp+' everytime you open root

													OR

		ii) 	creating/editing ~/rootlogon.C to include: 'gROOT->ProcessLine(".L /path/to/masstable.cpp+");'
				so that it runs this automatically for you. Find masstable.cpp and associated header and dat file here:
				https://github.com/zmp26/masstable

	Alternatively just remove the dependency and hardcode masses instead.

*/

#include <map>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <chrono>
#include "TFile.h"
#include "TH1D.h"
#include "TString.h"
#include "TDirectory.h"
#include "TLorentzVector.h"
#include "TVector3.h"
#include "invmass_mult3.h"
#include "invmass_mult3.cpp"//including .cpp for simple root macro purposes
#include "permHisto_mult3.h"//" above "
#include "permHisto_mult3.cpp"//" above "
#include "permHistoCorrelation_mult3.h"//" above "
#include "permHistoCorrelation_mult3.cpp"//" above "
#include "CutHandler.h"//" above "
#include "CutHandler.cpp"//" above "
#include "PixelHandler.h"//" above "
#include "PixelHandler.cpp"//" above "
#include "PID_structs.h"
#include "PID_Mult3.h"
#include "PID_Mult3.cpp"
#include "PID_Mult2.h"
#include "PID_Mult2.cpp"

// const double DEGRAD = M_PI / 180.;
// const double RADDEG = 180. / M_PI;

//commented below function until rewritten for updated TDirectory argument vs string filename 08/05/2026
// void B10ha_8BeHypothesis_kin4mcComparison(const char* input_filename, const char* cutlist_filename, double width_int, bool updateRecoilEx = true, bool updateIntermediateEx = true, int permCheck = 2){

// 	std::string s = input_filename;
// 	size_t last_dot = s.find_last_of(".");
// 	std::string stem = (last_dot == std::string::npos) ? s : s.substr(0, last_dot);

// 	std::string sabre_str = stem + "_SABREanalyzed8Be.root";
// 	std::string kin4mc_str = stem + "_kin4mcanalyzed8Be.root";

// 	const char* SABRE_output_filename = sabre_str.c_str();
// 	const char* kin4mc_output_filename = kin4mc_str.c_str();

// 	TMassTable fMassTable;
// 	fMassTable.Init("/home/zachpurcell/masstable/masstable.dat");

// 	Hypothesis4 b9_be8_hypothesis;
// 	b9_be8_hypothesis.name = "B10ha_8BeHypothesis";

// 	b9_be8_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
// 	b9_be8_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
// 	b9_be8_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_be8_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("B",9);
// 	b9_be8_hypothesis.mass_intermediate = fMassTable.GetNuclearMassMeV("Be",8);
// 	b9_be8_hypothesis.width_intermediate = width_int;
// 	b9_be8_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("H",1);
// 	b9_be8_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_be8_hypothesis.masses[2] = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_be8_hypothesis.beamEnergyMeV = 7.5;

// 	// b9_be8_hypothesis.recoilEx = recoilEx;
// 	// b9_be8_hypothesis.intermediateEx = intermediateEx;
// 	// b9_be8_hypothesis.intermediateExGate = intermediateExGate;

// 	TFile *infile = new TFile(input_filename, "READ");
// 	if(!infile || infile->IsZombie()){
// 		std::cerr << "Input file is bad: " << input_filename << std::endl;
// 		return;
// 	}

// 	TTree *intree = (TTree*)infile->Get("mult3");
// 	if(!intree){
// 		std::cerr << "Could not get TTree 'mult3' from " << input_filename << std::endl;
// 		return;
// 	}

// 	long numentries = intree->GetEntries();

// 	InvMass_Mult3 SABRE_analysis;;
// 	SABRE_analysis.Init(SABRE_output_filename);
// 	SABRE_analysis.SetHypothesis(b9_be8_hypothesis);
// 	// SABRE_analysis.SetGate1(gate1index);
// 	// SABRE_analysis.SetGate1MinMax(gate1minmax);
// 	// SABRE_analysis.SetGate2(gate2index);
// 	// SABRE_analysis.SetGate2MinMax(gate2minmax);
// 	// SABRE_analysis.SetGate3(gate3index);
// 	// SABRE_analysis.SetGate3MinMax(gate3minmax);
// 	CutHandler& cuthandler = SABRE_analysis.GetCutHandler();
// 	if(!cuthandler.LoadCutsFromConfig(cutlist_filename)){
// 		std::cerr << "Warning: could not load at least one cut from " << cutlist_filename << "!\n";
// 	}

// 	//test by printing cuts here:
// 	cuthandler.PrintCuts();

// 	InvMass_Mult3 kin4mc_analysis;
// 	kin4mc_analysis.Init(kin4mc_output_filename);
// 	kin4mc_analysis.SetHypothesis(b9_be8_hypothesis);
// 	// kin4mc_analysis.SetGate1(gate1index);
// 	// kin4mc_analysis.SetGate1MinMax(gate1minmax);
// 	// kin4mc_analysis.SetGate2(gate2index);
// 	// kin4mc_analysis.SetGate2MinMax(gate2minmax);
// 	// kin4mc_analysis.SetGate3(gate3index);
// 	// kin4mc_analysis.SetGate3MinMax(gate3minmax);
// 	cuthandler = kin4mc_analysis.GetCutHandler();
// 	if(!cuthandler.LoadCutsFromConfig(cutlist_filename)){
// 		std::cerr << "Warning: could not load at least one cut from " << cutlist_filename << "!\n";
// 	}

// 	//test by printing cuts here:
// 	cuthandler.PrintCuts();

// 	double kinmc_e[4], kinmc_theta[4], kinmc_phi[4];
// 	intree->SetBranchAddress("kin_e", kinmc_e);
// 	intree->SetBranchAddress("kin_theta", kinmc_theta);
// 	intree->SetBranchAddress("kin_phi", kinmc_phi);

// 	double Ex, SPSE, SPSTheta, SPSPhi;
// 	intree->SetBranchAddress("ExE", &Ex);
// 	intree->SetBranchAddress("SPSEnergy", &SPSE);
// 	intree->SetBranchAddress("SPSTheta", &SPSTheta);
// 	intree->SetBranchAddress("SPSPhi", &SPSPhi);

// 	double E[3], theta[3], phi[3];
// 	intree->SetBranchAddress("SabreRingEnergy_hit1", &E[0]);
// 	intree->SetBranchAddress("thetalab_hit1", &theta[0]);
// 	intree->SetBranchAddress("philab_hit1", &phi[0]);

// 	intree->SetBranchAddress("SabreRingEnergy_hit2", &E[1]);
// 	intree->SetBranchAddress("thetalab_hit2", &theta[1]);
// 	intree->SetBranchAddress("philab_hit2", &phi[1]);

// 	intree->SetBranchAddress("SabreRingEnergy_hit3", &E[2]);
// 	intree->SetBranchAddress("thetalab_hit3", &theta[2]);
// 	intree->SetBranchAddress("philab_hit3", &phi[2]);

// 	std::cout << "Starting analysis on " << numentries << " entries..." << std::endl;
// 	for(long i=0; i<numentries; i++){

// 		intree->GetEntry(i);

// 		double kinmc_bue[3], kinmc_butheta[3], kinmc_buphi[3];
// 		for(int j=0; j<3; j++){
// 			kinmc_bue[j] = kinmc_e[j+1];
// 			kinmc_butheta[j] = kinmc_theta[j+1];
// 			kinmc_buphi[j] = kinmc_phi[j+1];
// 		}

// 		//pass along SPS-informed recoil Ex if enabled:
// 		if(updateRecoilEx){
// 			SABRE_analysis.SetRecoilEx(Ex);
// 			//SABRE_analysis.SetExpectedCMValues();

// 			kin4mc_analysis.SetRecoilEx(Ex);
// 			//kin4mc_analysis.SetExpectedCMValues();
// 		}

// 		SABRE_analysis.AnalyzeEvent(E, theta, phi, SPSE, SPSTheta, SPSPhi, updateIntermediateEx);
// 		SABRE_analysis.FillEventHistograms(Ex);
// 		int numpasses_sabre = SABRE_analysis.CountPermPasses();
// 		SABRE_analysis.FillPermCounter();
// 		SABRE_analysis.FillSortedHisto(Ex);
// 		SABRE_analysis.FillSABRESumEVsSPS_Ex(Ex, E[0]+E[1]+E[2]);
// 		//if(numpasses_sabre == 2){
// 		SABRE_analysis.FillGatedEventHistograms(Ex); //due to symmetry of 8Be -> a + a, cases 012, 021 are identical, so check if 2 permutations pass intsead of just 1
// 		SABRE_analysis.FillPermCounter(true);
// 		//}
// 		SABRE_analysis.FillTree();
// 		//SABRE_analysis.FillGatedEventHistograms(); 

// 		kin4mc_analysis.AnalyzeEvent(kinmc_bue, kinmc_butheta, kinmc_buphi, kinmc_e[0], kinmc_theta[0], kinmc_phi[0], Ex, updateIntermediateEx);
// 		kin4mc_analysis.FillEventHistograms(Ex);
// 		int numpasses_kin4mc = kin4mc_analysis.CountPermPasses();
// 		kin4mc_analysis.FillPermCounter();
// 		kin4mc_analysis.FillSortedHisto(Ex);
// 		kin4mc_analysis.FillSABRESumEVsSPS_Ex(Ex, E[0]+E[1]+E[2]);
// 		//if(numpasses_kin4mc == 2){
// 		kin4mc_analysis.FillGatedEventHistograms(Ex); //due to symmetry of 8Be -> a + a, cases 012, 021 are identical, so check if 2 permutations pass intsead of just 1
// 		kin4mc_analysis.FillPermCounter(true);
// 		//}
// 		kin4mc_analysis.FillTree();
// 		//kin4mc_analysis.FillGatedEventHistograms();

// 		if(i % 1000 == 0){
// 			fprintf(stdout, "\rProgress: %.1f%% (%ld/%ld)",(float)i/numentries*100., i, numentries);
// 			fflush(stdout);
// 		}

// 	}

// 	SABRE_analysis.CloseAndWrite();
// 	kin4mc_analysis.CloseAndWrite();
// 	infile->Close();

// 	std::cout << "\n\nAnalysis complete!\n" << std::endl;
// 	std::cout << "SABRE output:  " << SABRE_output_filename << std::endl;
// 	std::cout << "kin4mc output: " << kin4mc_output_filename << std::endl;

// }

//commented below function until rewritten for updated TDirectory argument vs string filename 08/05/2026
// void B10ha_8BeHypothesis(const char* input_filename, const char* cutlist_filename, double width_int, bool updateRecoilEx = true, bool updateIntermediateEx = true, int permCheck = 2){

// 	std::string s = input_filename;
// 	size_t last_dot = s.find_last_of(".");
// 	std::string stem = (last_dot == std::string::npos) ? s : s.substr(0, last_dot);

// 	std::string sabre_str = stem + "_SABREanalyzed8Be.root";

// 	const char* SABRE_output_filename = sabre_str.c_str();

// 	TMassTable fMassTable;
// 	fMassTable.Init("/home/zachpurcell/masstable/masstable.dat");

// 	Hypothesis4 b9_be8_hypothesis;
// 	b9_be8_hypothesis.name = "B10ha_8BeHypothesis";

// 	b9_be8_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
// 	b9_be8_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
// 	b9_be8_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_be8_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("B",9);
// 	b9_be8_hypothesis.mass_intermediate = fMassTable.GetNuclearMassMeV("Be",8);
// 	b9_be8_hypothesis.width_intermediate = width_int;
// 	b9_be8_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("H",1);
// 	b9_be8_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_be8_hypothesis.masses[2] = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_be8_hypothesis.beamEnergyMeV = 7.5;

// 	TFile *infile = new TFile(input_filename, "READ");
// 	if(!infile || infile->IsZombie()){
// 		std::cerr << "Input file is bad: " << input_filename << std::endl;
// 		return;
// 	}

// 	TTree *intree = (TTree*)infile->Get("mult3");
// 	if(!intree){
// 		std::cerr << "Could not get TTree 'mult3' from " << input_filename << std::endl;
// 		return;
// 	}

// 	long numentries = intree->GetEntries();

// 	InvMass_Mult3 SABRE_analysis;;
// 	SABRE_analysis.Init(SABRE_output_filename);
// 	SABRE_analysis.SetHypothesis(b9_be8_hypothesis);
// 	//SABRE_analysis.InitCorrelationPlots();
// 	// SABRE_analysis.SetGate1(gate1index);
// 	// SABRE_analysis.SetGate1MinMax(gate1minmax);
// 	// SABRE_analysis.SetGate2(gate2index);
// 	// SABRE_analysis.SetGate2MinMax(gate2minmax);
// 	// SABRE_analysis.SetGate3(gate3index);
// 	// SABRE_analysis.SetGate3MinMax(gate3minmax);
// 	CutHandler& cuthandler = SABRE_analysis.GetCutHandler();
// 	if(!cuthandler.LoadCutsFromConfig(cutlist_filename)){
// 		std::cerr << "Warning: could not load at least one cut from " << cutlist_filename << "!\n";
// 	}

// 	//test by printing cuts here:
// 	cuthandler.PrintCuts();

// 	double Ex, SPSE, SPSTheta, SPSPhi;
// 	intree->SetBranchAddress("ExE", &Ex);
// 	intree->SetBranchAddress("SPSEnergy", &SPSE);
// 	intree->SetBranchAddress("SPSTheta", &SPSTheta);
// 	intree->SetBranchAddress("SPSPhi", &SPSPhi);

// 	double E[3], theta[3], phi[3];
// 	intree->SetBranchAddress("SabreRingEnergy_hit1", &E[0]);
// 	intree->SetBranchAddress("thetalab_hit1", &theta[0]);
// 	intree->SetBranchAddress("philab_hit1", &phi[0]);

// 	intree->SetBranchAddress("SabreRingEnergy_hit2", &E[1]);
// 	intree->SetBranchAddress("thetalab_hit2", &theta[1]);
// 	intree->SetBranchAddress("philab_hit2", &phi[1]);

// 	intree->SetBranchAddress("SabreRingEnergy_hit3", &E[2]);
// 	intree->SetBranchAddress("thetalab_hit3", &theta[2]);
// 	intree->SetBranchAddress("philab_hit3", &phi[2]);

// 	std::cout << "Starting analysis on " << numentries << " entries..." << std::endl;
// 	for(long i=0; i<numentries; i++){

// 		intree->GetEntry(i);

// 		//pass along SPS-informed recoil Ex if enabled:
// 		if(updateRecoilEx){
// 			SABRE_analysis.SetRecoilEx(Ex);
// 		}

// 		SABRE_analysis.AnalyzeEvent(E, theta, phi, SPSE, SPSTheta, SPSPhi, Ex, updateIntermediateEx);
// 		SABRE_analysis.FillEventHistograms(Ex);
// 		int numpasses_sabre = SABRE_analysis.CountPermPasses();
// 		SABRE_analysis.FillPermCounter();
// 		SABRE_analysis.FillSortedHisto(Ex);
// 		SABRE_analysis.FillSABRESumEVsSPS_Ex(Ex, E[0]+E[1]+E[2]);
// 		//if(numpasses_sabre == permCheck){ 
// 		SABRE_analysis.FillGatedEventHistograms(Ex); //due to symmetry of 8Be -> a + a, cases 012, 021 are identical, so check if 2 permutations pass intsead of just 1
// 		SABRE_analysis.FillPermCounter(true);
// 		//}
// 		SABRE_analysis.FillTree();

// 		if(i % 1000 == 0){
// 			fprintf(stdout, "\rProgress: %.1f%% (%ld/%ld)",(float)i/numentries*100., i, numentries);
// 			fflush(stdout);
// 		}

// 	}

// 	SABRE_analysis.CloseAndWrite();

// 	infile->Close();

// 	std::cout << "\n\nAnalysis complete!\n" << std::endl;
// 	std::cout << "SABRE output:  " << SABRE_output_filename << std::endl;
// }

//commented below function until rewritten for updated TDirectory argument vs string filename 08/05/2026
// void B10ha_5LiHypothesis_kin4mcComparison(const char* input_filename, const char* cutlist_filename, double width_int, bool updateRecoilEx = false, bool updateIntermediateEx = false){

// 	std::string s = input_filename;
// 	size_t last_dot = s.find_last_of(".");
// 	std::string stem = (last_dot == std::string::npos) ? s : s.substr(0, last_dot);

// 	std::string sabre_str = stem + "_SABREanalyzed5Li.root";
// 	std::string kin4mc_str = stem + "_kin4mcanalyzed5Li.root";

// 	const char* SABRE_output_filename = sabre_str.c_str();
// 	const char* kin4mc_output_filename = kin4mc_str.c_str();

// 	TMassTable fMassTable;
// 	fMassTable.Init("/home/zachpurcell/masstable/masstable.dat");

// 	Hypothesis4 b9_li5_hypothesis;
// 	b9_li5_hypothesis.name = "B10ha_5LiHypothesis";

// 	b9_li5_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
// 	b9_li5_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
// 	b9_li5_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_li5_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("B",9);
// 	b9_li5_hypothesis.mass_intermediate = fMassTable.GetNuclearMassMeV("Li",5);
// 	b9_li5_hypothesis.width_intermediate = width_int;
// 	b9_li5_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_li5_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("H",1);
// 	b9_li5_hypothesis.masses[2] = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_li5_hypothesis.beamEnergyMeV = 7.5;

// 	TFile *infile = new TFile(input_filename, "READ");
// 	if(!infile || infile->IsZombie()){
// 		std::cerr << "Input file is bad: " << input_filename << std::endl;
// 		return;
// 	}

// 	TTree *intree = (TTree*)infile->Get("mult3");
// 	if(!intree){
// 		std::cerr << "Could not get TTree 'mult3' from " << input_filename << std::endl;
// 		return;
// 	}

// 	long numentries = intree->GetEntries();

// 	InvMass_Mult3 SABRE_analysis;;
// 	SABRE_analysis.Init(SABRE_output_filename);
// 	SABRE_analysis.SetHypothesis(b9_li5_hypothesis);
// 	// SABRE_analysis.SetGate1(gate1index);
// 	// SABRE_analysis.SetGate1MinMax(gate1minmax);
// 	// SABRE_analysis.SetGate2(gate2index);
// 	// SABRE_analysis.SetGate2MinMax(gate2minmax);
// 	// SABRE_analysis.SetGate3(gate3index);
// 	// SABRE_analysis.SetGate3MinMax(gate3minmax);
// 	CutHandler& cuthandler = SABRE_analysis.GetCutHandler();
// 	if(!cuthandler.LoadCutsFromConfig(cutlist_filename)){
// 		std::cerr << "Warning: could not load at least one cut from " << cutlist_filename << "!\n";
// 	}

// 	//test by printing cuts here:
// 	cuthandler.PrintCuts();

// 	InvMass_Mult3 kin4mc_analysis;
// 	kin4mc_analysis.Init(kin4mc_output_filename);
// 	kin4mc_analysis.SetHypothesis(b9_li5_hypothesis);
// 	// kin4mc_analysis.SetGate1(gate1index);
// 	// kin4mc_analysis.SetGate1MinMax(gate1minmax);
// 	// kin4mc_analysis.SetGate2(gate2index);
// 	// kin4mc_analysis.SetGate2MinMax(gate2minmax);
// 	// kin4mc_analysis.SetGate3(gate3index);
// 	// kin4mc_analysis.SetGate3MinMax(gate3minmax);
// 	cuthandler = kin4mc_analysis.GetCutHandler();
// 	if(!cuthandler.LoadCutsFromConfig(cutlist_filename)){
// 		std::cerr << "Warning: could not load at least one cut from " << cutlist_filename << "!\n";
// 	}

// 	//test by printing cuts here:
// 	cuthandler.PrintCuts();

// 	double kinmc_e[4], kinmc_theta[4], kinmc_phi[4];
// 	intree->SetBranchAddress("kin_e", kinmc_e);
// 	intree->SetBranchAddress("kin_theta", kinmc_theta);
// 	intree->SetBranchAddress("kin_phi", kinmc_phi);

// 	double Ex, SPSE, SPSTheta, SPSPhi;
// 	intree->SetBranchAddress("ExE", &Ex);
// 	intree->SetBranchAddress("SPSEnergy", &SPSE);
// 	intree->SetBranchAddress("SPSTheta", &SPSTheta);
// 	intree->SetBranchAddress("SPSPhi", &SPSPhi);

// 	double E[3], theta[3], phi[3];
// 	intree->SetBranchAddress("SabreRingEnergy_hit1", &E[0]);
// 	intree->SetBranchAddress("thetalab_hit1", &theta[0]);
// 	intree->SetBranchAddress("philab_hit1", &phi[0]);

// 	intree->SetBranchAddress("SabreRingEnergy_hit2", &E[1]);
// 	intree->SetBranchAddress("thetalab_hit2", &theta[1]);
// 	intree->SetBranchAddress("philab_hit2", &phi[1]);

// 	intree->SetBranchAddress("SabreRingEnergy_hit3", &E[2]);
// 	intree->SetBranchAddress("thetalab_hit3", &theta[2]);
// 	intree->SetBranchAddress("philab_hit3", &phi[2]);

// 	std::cout << "Starting analysis on " << numentries << " entries..." << std::endl;

// 	for(long i=0; i<numentries; i++){

// 		intree->GetEntry(i);

// 		double kinmc_bue[3], kinmc_butheta[3], kinmc_buphi[3];
// 		for(int j=0; j<3; j++){
// 			kinmc_bue[j] = kinmc_e[j+1];
// 			kinmc_butheta[j] = kinmc_theta[j+1];
// 			kinmc_buphi[j] = kinmc_phi[j+1];
// 		}

// 		//pass along SPS-informed recoil Ex if enabled:
// 		if(updateRecoilEx){
// 			SABRE_analysis.SetRecoilEx(Ex);
// 			//SABRE_analysis.SetExpectedCMValues();

// 			kin4mc_analysis.SetRecoilEx(Ex);
// 			//kin4mc_analysis.SetExpectedCMValues();
// 		}

// 		SABRE_analysis.AnalyzeEvent(E, theta, phi, SPSE, SPSTheta, SPSPhi, Ex, updateIntermediateEx);
// 		SABRE_analysis.FillEventHistograms(Ex);
// 		int numpasses_sabre = SABRE_analysis.CountPermPasses();
// 		SABRE_analysis.FillPermCounter();
// 		SABRE_analysis.FillSortedHisto(Ex);
// 		SABRE_analysis.FillSABRESumEVsSPS_Ex(Ex, E[0]+E[1]+E[2]);
// 		//if(numpasses_sabre == 1){
// 		SABRE_analysis.FillGatedEventHistograms(Ex);
// 		SABRE_analysis.FillPermCounter(true);
// 		//}
// 		SABRE_analysis.FillTree();

// 		kin4mc_analysis.AnalyzeEvent(kinmc_bue, kinmc_butheta, kinmc_buphi, kinmc_e[0], kinmc_theta[0], kinmc_phi[0], Ex, updateIntermediateEx);
// 		kin4mc_analysis.FillEventHistograms(Ex);
// 		int numpasses_kin4mc = kin4mc_analysis.CountPermPasses();
// 		kin4mc_analysis.FillPermCounter();
// 		kin4mc_analysis.FillSortedHisto(Ex);
// 		kin4mc_analysis.FillSABRESumEVsSPS_Ex(Ex, E[0]+E[1]+E[2]);
// 		//if(numpasses_kin4mc == 1){
// 		kin4mc_analysis.FillGatedEventHistograms(Ex);
// 		kin4mc_analysis.FillPermCounter(true);
// 		//}
// 		kin4mc_analysis.FillTree();

// 		if(i % 1000 == 0){
// 			fprintf(stdout, "\rProgress: %.1f%% (%ld/%ld)",(float)i/numentries*100., i, numentries);
// 			fflush(stdout);
// 		}

// 	}

// 	SABRE_analysis.CloseAndWrite();
// 	kin4mc_analysis.CloseAndWrite();
// 	infile->Close();

// 	std::cout << "\n\nAnalysis complete!\n" << std::endl;
// 	std::cout << "SABRE output:  " << SABRE_output_filename << std::endl;
// 	std::cout << "kin4mc output: " << kin4mc_output_filename << std::endl;

// }
//commented below function until rewritten for updated TDirectory argument vs string filename 08/05/2026
// void B10ha_5LiHypothesis(const char* input_filename, const char* cutlist_filename, double width_int, bool updateRecoilEx = true, bool updateIntermediateEx = true){

// 	std::string s = input_filename;
// 	size_t last_dot = s.find_last_of(".");
// 	std::string stem = (last_dot == std::string::npos) ? s : s.substr(0, last_dot);

// 	std::string sabre_str = stem + "_SABREanalyzed5Li.root";
// 	std::string kin4mc_str = stem + "_kin4mcanalyzed5Li.root";

// 	const char* SABRE_output_filename = sabre_str.c_str();
// 	const char* kin4mc_output_filename = kin4mc_str.c_str();

// 	TMassTable fMassTable;
// 	fMassTable.Init("/home/zachpurcell/masstable/masstable.dat");

// 	Hypothesis4 b9_li5_hypothesis;
// 	b9_li5_hypothesis.name = "B10ha_5LiHypothesis";

// 	b9_li5_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
// 	b9_li5_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
// 	b9_li5_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_li5_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("B",9);
// 	b9_li5_hypothesis.mass_intermediate = fMassTable.GetNuclearMassMeV("Li",5);
// 	b9_li5_hypothesis.width_intermediate = width_int;
// 	b9_li5_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_li5_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("H",1);
// 	b9_li5_hypothesis.masses[2] = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_li5_hypothesis.beamEnergyMeV = 7.5;

// 	TFile *infile = new TFile(input_filename, "READ");
// 	if(!infile || infile->IsZombie()){
// 		std::cerr << "Input file is bad: " << input_filename << std::endl;
// 		return;
// 	}

// 	TTree *intree = (TTree*)infile->Get("mult3");
// 	if(!intree){
// 		std::cerr << "Could not get TTree 'mult3' from " << input_filename << std::endl;
// 		return;
// 	}

// 	long numentries = intree->GetEntries();

// 	InvMass_Mult3 SABRE_analysis;;
// 	//SABRE_analysis.Init(SABRE_output_filename);
// 	SABRE_analysis.SetHypothesis(b9_li5_hypothesis);
// 	// SABRE_analysis.SetGate1(gate1index);
// 	// SABRE_analysis.SetGate1MinMax(gate1minmax);
// 	// SABRE_analysis.SetGate2(gate2index);
// 	// SABRE_analysis.SetGate2MinMax(gate2minmax);
// 	// SABRE_analysis.SetGate3(gate3index);
// 	// SABRE_analysis.SetGate3MinMax(gate3minmax);
// 	CutHandler& cuthandler = SABRE_analysis.GetCutHandler();
// 	if(!cuthandler.LoadCutsFromConfig(cutlist_filename)){
// 		std::cerr << "Warning: could not load at least one cut from " << cutlist_filename << "!\n";
// 	}

// 	//test by printing cuts here:
// 	cuthandler.PrintCuts();

// 	double Ex, SPSE, SPSTheta, SPSPhi;
// 	intree->SetBranchAddress("ExE", &Ex);
// 	intree->SetBranchAddress("SPSEnergy", &SPSE);
// 	intree->SetBranchAddress("SPSTheta", &SPSTheta);
// 	intree->SetBranchAddress("SPSPhi", &SPSPhi);

// 	double E[3], theta[3], phi[3];
// 	intree->SetBranchAddress("SabreRingEnergy_hit1", &E[0]);
// 	intree->SetBranchAddress("thetalab_hit1", &theta[0]);
// 	intree->SetBranchAddress("philab_hit1", &phi[0]);

// 	intree->SetBranchAddress("SabreRingEnergy_hit2", &E[1]);
// 	intree->SetBranchAddress("thetalab_hit2", &theta[1]);
// 	intree->SetBranchAddress("philab_hit2", &phi[1]);

// 	intree->SetBranchAddress("SabreRingEnergy_hit3", &E[2]);
// 	intree->SetBranchAddress("thetalab_hit3", &theta[2]);
// 	intree->SetBranchAddress("philab_hit3", &phi[2]);

// 	std::cout << "Starting analysis on " << numentries << " entries..." << std::endl;

// 	for(long i=0; i<numentries; i++){

// 		intree->GetEntry(i);

// 		//pass along SPS-informed recoil Ex if enabled:
// 		if(updateRecoilEx){
// 			SABRE_analysis.SetRecoilEx(Ex);
// 		}

// 		SABRE_analysis.AnalyzeEvent(E, theta, phi, SPSE, SPSTheta, SPSPhi, Ex, updateIntermediateEx);
// 		SABRE_analysis.FillEventHistograms(Ex);
// 		int numpasses_sabre = SABRE_analysis.CountPermPasses();
// 		SABRE_analysis.FillPermCounter();
// 		SABRE_analysis.FillSortedHisto(Ex);
// 		SABRE_analysis.FillSABRESumEVsSPS_Ex(Ex, E[0]+E[1]+E[2]);
// 		//std::cout << "numpasses_sabre = " << numpasses_sabre << "\n";
// 		//if(numpasses_sabre == 1){
// 		SABRE_analysis.FillGatedEventHistograms(Ex);
// 		SABRE_analysis.FillPermCounter(true);
// 		//}
// 		SABRE_analysis.FillTree();

// 		if(i % 1000 == 0){
// 			fprintf(stdout, "\rProgress: %.1f%% (%ld/%ld)",(float)i/numentries*100., i, numentries);
// 			fflush(stdout);
// 		}

// 	}

// 	SABRE_analysis.CloseAndWrite();
// 	infile->Close();

// 	std::cout << "\n\nAnalysis complete!\n" << std::endl;
// 	std::cout << "SABRE output:  " << SABRE_output_filename << std::endl;

// }

//commented below function until rewritten for updated TDirectory argument vs string filename 08/05/2026
// void tempDoAll_5LiHypothesis(const char* cutlist_filename, bool updateRecoilEx = false, bool updateIntermediateEx = false){

// 	std::vector<int> intExs;
// 	std::vector<std::pair<double,double>> intEminmax;
// 	std::vector<std::pair<double,double>> intVCMminmax;
// 	std::vector<std::pair<double,double>> frag1VCMminmax;

// 	//update above values for 5Li case (just copied from 8Be)
// 	std::pair<double,double> minmax1, minmax2, minmax3;

// 	//for(auto const &intEx : intExs){
// 	for(size_t i=0; i<intExs.size(); i++){
// 		int intEx = intExs.at(i);
// 		TString filename = Form("may16/det/b10ha_7.5MeV_9B_ex%dkeV_a5Li_ex0keV_1000k_tree_mult3.root", intEx);

// 		B10ha_5LiHypothesis(filename.Data(), cutlist_filename, updateRecoilEx, updateIntermediateEx);
// 	}
// }


// void B10ha_CombinedAnalysis(const char* input_filename, const char* cutlist_8Be, const char* cutlist_5Li, double width_8Be = 0.00000557, double width_5Li = 1.23, bool updateRecoilEx=true, bool updateIntermediateEx=true){

// 	std::string s = input_filename;
// 	size_t last_dot = s.find_last_of(".");
// 	std::string stem = (last_dot == std::string::npos ? s : s.substr(0, last_dot));
// 	std::string out_str = stem + "_SABRE_GlobalMinAnalysis.root";

// 	TMassTable fMassTable;
// 	fMassTable.Init("/home/zachpurcell/masstable/masstable.dat");

// 	Hypothesis4 hyp_8Be;
// 	hyp_8Be.name = "B10ha_8BeHypothesis";
// 	hyp_8Be.mass_target        = fMassTable.GetNuclearMassMeV("B", 10);
// 	hyp_8Be.mass_beam          = fMassTable.GetNuclearMassMeV("He", 3);
// 	hyp_8Be.mass_ejectile      = fMassTable.GetNuclearMassMeV("He", 4);
// 	hyp_8Be.mass_recoil        = fMassTable.GetNuclearMassMeV("B", 9);
// 	hyp_8Be.mass_intermediate  = fMassTable.GetNuclearMassMeV("Be", 8);
// 	hyp_8Be.width_intermediate = width_8Be;
// 	hyp_8Be.masses[0]          = fMassTable.GetNuclearMassMeV("H", 1);  // Proton
// 	hyp_8Be.masses[1]          = fMassTable.GetNuclearMassMeV("He", 4); // Alpha 1
// 	hyp_8Be.masses[2]          = fMassTable.GetNuclearMassMeV("He", 4); // Alpha 2
// 	hyp_8Be.beamEnergyMeV      = 7.5;

// 	Hypothesis4 hyp_5Li;
// 	hyp_5Li.name = "B10ha_5LiHypothesis";
// 	hyp_5Li.mass_target       = fMassTable.GetNuclearMassMeV("B", 10);
// 	hyp_5Li.mass_beam         = fMassTable.GetNuclearMassMeV("He", 3);
// 	hyp_5Li.mass_ejectile     = fMassTable.GetNuclearMassMeV("He", 4);
// 	hyp_5Li.mass_recoil       = fMassTable.GetNuclearMassMeV("B", 9);
// 	hyp_5Li.mass_intermediate = fMassTable.GetNuclearMassMeV("Li", 5);
// 	hyp_5Li.width_intermediate = width_5Li;
// 	hyp_5Li.masses[0]         = fMassTable.GetNuclearMassMeV("He", 4); // Alpha
// 	hyp_5Li.masses[1]         = fMassTable.GetNuclearMassMeV("H", 1);  // Proton
// 	hyp_5Li.masses[2]         = fMassTable.GetNuclearMassMeV("He", 4); // Alpha
// 	hyp_5Li.beamEnergyMeV     = 7.5;

// 	TFile *infile = TFile::Open(input_filename, "READ");
// 	if(!infile || infile->IsZombie()){
// 		std::cerr << "Error: Cannot open input file " << input_filename << std::endl;
// 		return;
// 	}

// 	TTree *intree = (TTree*)infile->Get("mult3");
// 	if(!intree){
// 		std::cerr << "Error: Cannot get TTree 'mult3'!" << std::endl;
// 		infile->Close();
// 		return;
// 	}

// 	long numentries = intree->GetEntries();


// 	TFile *outfile = new TFile(out_str.c_str(), "RECREATE");

// 	TDirectory* dir_8Be = outfile->mkdir("p8Be");
// 	TDirectory* dir_5Li = outfile->mkdir("a5Li");

// /*outtree = new 

// 	InvMass_Mult3 SABRE_analysis;;
// 	SABRE_analysis.Init(SABRE_output_filename);
// 	SABRE_analysis.SetHypothesis(b9_li5_hypothesis);
// 	// SABRE_analysis.SetGate1(gate1index);
// 	// SABRE_analysis.SetGate1MinMax(gate1minmax);
// 	// SABRE_analysis.SetGate2(gate2index);
// 	// SABRE_analysis.SetGate2MinMax(gate2minmax);
// 	// SABRE_analysis.SetGate3(gate3index);
// 	// SABRE_analysis.SetGate3MinMax(gate3minmax);
// 	CutHandler& cuthandler = SABRE_analysis.GetCutHandler();
// 	if(!cuthandler.LoadCutsFromConfig(cutlist_filename)){
// 		std::cerr << "Warning: could not load at least one cut from " << cutlist_filename << "!\n";
// 	}

// 	//test by printing cuts here:
// 	cuthandler.PrintCuts();

// */

// 	InvMass_Mult3 analysis_8Be;
// 	analysis_8Be.Init(dir_8Be);
// 	analysis_8Be.SetHypothesis(hyp_8Be);
// 	if(!analysis_8Be.GetCutHandler().LoadCutsFromConfig(cutlist_8Be)){
// 		std::cerr << "Warning: Could not load 8Be cut list from " << cutlist_8Be << std::endl;
// 	}
// 	analysis_8Be.GetCutHandler().PrintCuts();

// 	InvMass_Mult3 analysis_5Li;
// 	analysis_5Li.Init(dir_5Li);
// 	analysis_5Li.SetHypothesis(hyp_5Li);
// 	if (!analysis_5Li.GetCutHandler().LoadCutsFromConfig(cutlist_5Li)) {
// 		std::cerr << "Warning: Could not load 5Li cuts from " << cutlist_5Li << std::endl;
// 	}
// 	analysis_5Li.GetCutHandler().PrintCuts();

// 	outfile->cd();
// 	TH1D* hChannelSelection = new TH1D("hChannelSelection", "Winning Channel Assignment; Channel; Counts", 3, -0.5, 2.5);
// 	hChannelSelection->GetXaxis()->SetBinLabel(1, "8Be Chosen");
// 	hChannelSelection->GetXaxis()->SetBinLabel(2, "5Li Chosen");
// 	hChannelSelection->GetXaxis()->SetBinLabel(3, "Neither Chosen");

// 	TH1D* hGlobalPermutationSelection = new TH1D("hGlobalPermutationSelection", "Global Minimum Selected Permutation; (8Be: bin 1-6, 5Li: bin 7-12)", 12, 0.5, 12.5);
// 	const char* permLabels[6] = {"012", "021", "102", "120", "201", "210"};
// 	for(int k=0; k<6; k++){
// 		hGlobalPermutationSelection->GetXaxis()->SetBinLabel(k+1, Form("8Be_%s", permLabels[k]));
// 		hGlobalPermutationSelection->GetXaxis()->SetBinLabel(k+7, Form("5Li_%s", permLabels[k]));
// 	}

// 	TH2D* hChi2Comparison = new TH2D("hChi2Comparison", "Best Perm #chi^{2}, 8Be vs 5Li; 5Li; 8Be", 150, 0, 15, 150, 0, 15);

// 	double Ex, SPSE, SPSTheta, SPSPhi;
// 	intree->SetBranchAddress("ExE", &Ex);
// 	intree->SetBranchAddress("SPSEnergy", &SPSE);
// 	intree->SetBranchAddress("SPSTheta", &SPSTheta);
// 	intree->SetBranchAddress("SPSPhi", &SPSPhi);

// 	double E[3], theta[3], phi[3];
// 	intree->SetBranchAddress("SabreRingEnergy_hit1", &E[0]);
// 	intree->SetBranchAddress("thetalab_hit1", &theta[0]);
// 	intree->SetBranchAddress("philab_hit1", &phi[0]);

// 	intree->SetBranchAddress("SabreRingEnergy_hit2", &E[1]);
// 	intree->SetBranchAddress("thetalab_hit2", &theta[1]);
// 	intree->SetBranchAddress("philab_hit2", &phi[1]);

// 	intree->SetBranchAddress("SabreRingEnergy_hit3", &E[2]);
// 	intree->SetBranchAddress("thetalab_hit3", &theta[2]);
// 	intree->SetBranchAddress("philab_hit3", &phi[2]);

// 	std::cout << "Starting global minimum comparison on " << numentries << " entries..." << std::endl;

// 	for(long i=0; i<numentries; i++){
// 		intree->GetEntry(i);

// 		if(updateRecoilEx){
// 			analysis_8Be.SetRecoilEx(Ex);
// 			analysis_5Li.SetRecoilEx(Ex);
// 		}

// 		analysis_8Be.AnalyzeEvent(E, theta, phi, SPSE, SPSTheta, SPSPhi, Ex, updateIntermediateEx);
// 		analysis_5Li.AnalyzeEvent(E, theta, phi, SPSE, SPSTheta, SPSPhi, Ex, updateIntermediateEx);

// 		const auto& chi2_8Be = analysis_8Be.GetEventChi2s();
// 		const auto& chi2_5Li = analysis_5Li.GetEventChi2s();

// 		auto it_8Be = std::min_element(chi2_8Be.begin(), chi2_8Be.end());
// 		auto it_5Li = std::min_element(chi2_5Li.begin(), chi2_5Li.end());

// 		double min_chi2_8Be = (it_8Be != chi2_8Be.end()) ? *it_8Be : 1e9;
// 		double min_chi2_5Li = (it_5Li != chi2_5Li.end()) ? *it_5Li : 1e9;

// 		int idx_8Be = (it_8Be != chi2_8Be.end()) ? std::distance(chi2_8Be.begin(), it_8Be) : -1;
// 		int idx_5Li = (it_5Li != chi2_5Li.end()) ? std::distance(chi2_5Li.begin(), it_5Li) : -1;

// 		hChi2Comparison->Fill(min_chi2_5Li, min_chi2_8Be);

// 		if(min_chi2_8Be <= min_chi2_5Li && min_chi2_8Be < 1e8){//note that for now, <= check picks 8Be for tie breaker
// 			//8Be channel wins
// 			hChannelSelection->Fill(0);

// 			if(idx_8Be >= 0 && idx_8Be < 6){
// 				hGlobalPermutationSelection->Fill(idx_8Be+1);
// 			}

// 			analysis_8Be.FillEventHistograms(Ex);
// 			analysis_8Be.FillPermCounter();
// 			analysis_8Be.FillSortedHisto(Ex);
// 			analysis_8Be.FillSABRESumEVsSPS_Ex(Ex, E[0] + E[1] + E[2]);
// 			analysis_8Be.FillGatedEventHistograms(Ex);
// 			analysis_8Be.FillPermCounter(true);
// 			analysis_8Be.FillTree();

// 		} else if(min_chi2_5Li < min_chi2_8Be && min_chi2_5Li < 1e8) {
// 			//5Li channel wins
// 			hChannelSelection->Fill(1);

// 			if (idx_5Li >= 0 && idx_5Li < 6) {
// 				hGlobalPermutationSelection->Fill(idx_5Li + 7);
// 			}

// 			analysis_5Li.FillEventHistograms(Ex);
// 			analysis_5Li.FillPermCounter();
// 			analysis_5Li.FillSortedHisto(Ex);
// 			analysis_5Li.FillSABRESumEVsSPS_Ex(Ex, E[0] + E[1] + E[2]);
// 			analysis_5Li.FillGatedEventHistograms(Ex);
// 			analysis_5Li.FillPermCounter(true);
// 			analysis_5Li.FillTree();
// 		} else {
// 			hChannelSelection->Fill(2);
// 		}


// 		if(i % 1000 == 0){
// 			fprintf(stdout, "\rProgress: %.1f%% (%ld/%ld)", (float)i*100./numentries, i, numentries);
// 			fflush(stdout);
// 		}

// 	}

// 	outfile->Write();
// 	outfile->Close();
// 	infile->Close();

// 	std::cout << "\n\nGlobal Minimum Analysis Complete!\n";
// 	std::cout << "Output saved to: " << out_str << std::endl;
// }

// void B10ha_PID(const char* input_filename){

// 	std::string s = input_filename;
// 	size_t last_dot = s.find_last_of(".");
// 	std::string stem = (last_dot == std::string::npos ? s : s.substr(0, last_dot));
// 	std::string out_str = stem + "_SABRE_PID.root";

// 	TMassTable fMassTable;
// 	fMassTable.Init("/home/zachpurcell/masstable/masstable.dat");

// 	PIDHypothesis hypothesis;
// 	hypothesis.name = "paa";
// 	hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
// 	hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
// 	hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
// 	hypothesis.beamEnergyMeV = 7.5;
// 	hypothesis.final_masses[0] = fMassTable.GetNuclearMassMeV("H",1);
// 	hypothesis.final_particles[0] = "p";
// 	hypothesis.final_masses[1] = fMassTable.GetNuclearMassMeV("He",4);
// 	hypothesis.final_particles[1] = "#alpha";
// 	hypothesis.final_masses[2] = fMassTable.GetNuclearMassMeV("He",4);
// 	hypothesis.final_particles[2] = "#alpha";

// 	std::ifstream infile(input_filename);
// 	if (!infile.is_open()) {
// 		std::cerr << "Error: Could not open input file " << input_filename << std::endl;
// 		return;
// 	}

// 	TFile *outfile = new TFile(out_str.c_str(), "RECREATE");
// 	outfile->cd();
// 	TH1D *hProtonPicks = new TH1D("hProtonPicks", "Hit Index Assigned to Proton", 3, -0.5, 2.5);
// 	hProtonPicks->SetDirectory(outfile);

// 	PID_Mult3 pidSolver;
// 	pidSolver.SetHypothesis(hypothesis);

// 	pidSolver.SetResolution(0.05, 1.0, 1.0);
// 	pidSolver.SetSPSResolution(0.015, 0.5, 0.5);

// 	pidSolver.SetChi2Cut(10.);

// 	pidSolver.InitDiagnostics(outfile);


// 	TTree *outtree = new TTree("PID_Mult3", "PID_Mult3");
// 	outtree->SetDirectory(outfile);

// 	double sps_e, sps_theta, sps_phi;
// 	double e[3], theta[3], phi[3];

// 	int bestPermIndex;
// 	double bestChi2;
// 	bool passesCut;
// 	int proton_hit_index, alpha_hit_index1, alpha_hit_index2;//alpha_hit_index 1/2 does NOT necessarily refer to alpha1/alpha2 (we cannot tell these apart yet)

// 	TLorentzVector proton, alpha1, alpha2, recoil, intermediate;//again, alpha1/alpha2 are NOT necessarily the first/second alpha if sequential decay!
// 	double residual_px, residual_py, residual_pz, residual_pmag;

// 	double m2_aa, m2_pa1, m2_pa2;
// 	double ExSPS;

// 	outtree->Branch("bestPermIndex", &bestPermIndex, "bestPermIndex/I");
// 	outtree->Branch("bestChi2", &bestChi2, "bestChi2/D");
// 	outtree->Branch("passesCut", &passesCut, "passesCut/O");

// 	outtree->Branch("protonHitIndex", &proton_hit_index, "protonHitIndex/I");
// 	outtree->Branch("alphaHitIndex1", &alpha_hit_index1, "alphaHitIndex1/I");
// 	outtree->Branch("alphaHitIndex2", &alpha_hit_index2, "alphaHitIndex2/I");

// 	// Reconstructed 4-vectors
// 	outtree->Branch("P4_proton", &proton);
// 	outtree->Branch("P4_alpha1", &alpha1);
// 	outtree->Branch("P4_alpha2", &alpha2);
// 	outtree->Branch("P4_recoil", &recoil); // Invariant mass of (p + a1 + a2)

// 	outtree->Branch("m2_aa", &m2_aa);
// 	outtree->Branch("m2_pa1", &m2_pa1);
// 	outtree->Branch("m2_pa2", &m2_pa2);

// 	outtree->Branch("ExSPS", &ExSPS);

// 	// Residual momentum
// 	outtree->Branch("residual_px", &residual_px, "residual_px/D");
// 	outtree->Branch("residual_py", &residual_py, "residual_py/D");
// 	outtree->Branch("residual_pz", &residual_pz, "residual_pz/D");
// 	outtree->Branch("residual_Pmag", &residual_pmag, "residual_Pmag/D");


// 	long eventCount = 0;
// 	while(infile >> sps_e >> sps_theta >> sps_phi >> e[0] >> theta[0] >> phi[0] >> e[1] >> theta[1] >> phi[1] >> e[2] >> theta[2] >> phi[2]){

// 		PIDResult_Mult3 res = pidSolver.EvaluateEvent(e, theta, phi, sps_e, sps_theta, sps_phi);

// 		bestPermIndex = res.bestChi2Index;
// 		bestChi2 = res.bestChi2;
// 		passesCut = res.passesCut;

// 		//std::cout << "bestPermIndex = " << bestPermIndex << "\tbestChi2 = " << bestChi2 << "\npassesCut = " << passesCut << "\n";

// 		proton_hit_index = res.hit_indices[0];
// 		alpha_hit_index1 = res.hit_indices[1];
// 		alpha_hit_index2 = res.hit_indices[2];

// 		residual_px = res.missing_px;
// 		residual_py = res.missing_py;
// 		residual_pz = res.missing_pz;
// 		residual_pmag = res.missing_Pmag;

// 		m2_aa = res.m2_aa;
// 		m2_pa1 = res.m2_pa1;
// 		m2_pa2 = res.m2_pa2;

// 		if(bestPermIndex >= 0){
// 			auto buildP4 = [](double E, double theta, double phi, double m){
// 				double p = std::sqrt(E*(E+2.*m));
// 				double rad_th = theta*M_PI/180.;
// 				double rad_ph = phi*M_PI/180.;
// 				return TLorentzVector(
// 						p*std::sin(rad_th)*std::cos(rad_ph),
// 						p*std::sin(rad_th)*std::sin(rad_ph),
// 						p*std::cos(rad_th),
// 						E+m
// 					);
// 			};
// 			hProtonPicks->Fill(proton_hit_index);
// 			proton = buildP4(e[proton_hit_index], theta[proton_hit_index], phi[proton_hit_index], hypothesis.final_masses[0]);
// 			alpha1 = buildP4(e[alpha_hit_index1], theta[alpha_hit_index1], phi[alpha_hit_index1], hypothesis.final_masses[1]);
// 			alpha2 = buildP4(e[alpha_hit_index2], theta[alpha_hit_index2], phi[alpha_hit_index2], hypothesis.final_masses[2]);
// 			recoil = proton + alpha1 + alpha2;
// 		} else {
// 			proton.SetPxPyPzE(0.,0.,0.,0.);
// 			alpha1.SetPxPyPzE(0.,0.,0.,0.);
// 			alpha2.SetPxPyPzE(0.,0.,0.,0.);
// 			recoil.SetPxPyPzE(0.,0.,0.,0.);
// 		}

// 		outtree->Fill();
// 		eventCount++;

// 		if(eventCount % 10000 == 0){
// 			std::cout << "Processed " << eventCount << " events..." << std::endl;
// 		}

// 	}

// 	infile.close();

// 	outfile->cd();
// 	outfile->Write();
// 	outfile->Close();
// 	delete outfile;

// 	std::cout << "Finished! Processed " << eventCount << " events. Output stored in " << out_str.c_str() << std::endl;

// }

void B10ha_SABREPID(const char* input_filename, TString simchan="paa"){
	std::string s = input_filename;
	size_t last_dot = s.find_last_of(".");
	std::string stem = (last_dot == std::string::npos ? s : s.substr(0, last_dot));
	std::string out_str = stem + "_SABREPID.root";

	TMassTable fMassTable;
	fMassTable.Init("/home/zachpurcell/masstable/masstable.dat");

	double massgs_5Li = fMassTable.GetNuclearMassMeV("Li",5);
	double massgs_8Be = fMassTable.GetNuclearMassMeV("Be",8);
	double massgs_9B = fMassTable.GetNuclearMassMeV("B", 9);

	double mass_p = fMassTable.GetNuclearMassMeV("H",1);
	double mass_a = fMassTable.GetNuclearMassMeV("He",4);

	PIDHypothesis hypothesis;
	hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
	hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
	hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
	hypothesis.beamEnergyMeV = 7.5;
	if(simchan.EqualTo("paa")){
		hypothesis.name = "paa";
		hypothesis.final_masses[0] = fMassTable.GetNuclearMassMeV("H",1);
		hypothesis.final_particles[0] = "p";
		hypothesis.final_masses[1] = fMassTable.GetNuclearMassMeV("He",4);
		hypothesis.final_particles[1] = "#alpha";
		hypothesis.final_masses[2] = fMassTable.GetNuclearMassMeV("He",4);
		hypothesis.final_particles[2] = "#alpha";
	} else if(simchan.EqualTo("apa")){
		hypothesis.name = "apa";
		hypothesis.final_masses[0] = fMassTable.GetNuclearMassMeV("He",4);
		hypothesis.final_particles[0] = "#alpha";
		hypothesis.final_masses[1] = fMassTable.GetNuclearMassMeV("H",1);
		hypothesis.final_particles[1] = "p";
		hypothesis.final_masses[2] = fMassTable.GetNuclearMassMeV("He",4);
		hypothesis.final_particles[2] = "#alpha";
	}

	TFile *infile = TFile::Open(input_filename, "READ");
	if(!infile || infile->IsZombie()){
		std::cerr << "Error: Cannot open input file " << input_filename << std::endl;
		return;
	}

	TTree *intree = (TTree*)infile->Get("mult3");
	if(!intree){
		std::cerr << "Error: cannot get TTree 'mult3' from " << input_filename << std::endl;
		infile->Close();
		return;
	}

	double Ex, SPSE, SPSTheta, SPSPhi;
	intree->SetBranchAddress("ExE", &Ex);
	intree->SetBranchAddress("SPSEnergy", &SPSE);
	intree->SetBranchAddress("SPSTheta", &SPSTheta);
	intree->SetBranchAddress("SPSPhi", &SPSPhi);

	double E[3], theta[3], phi[3];
	intree->SetBranchAddress("SabreRingEnergy_hit1", &E[0]);
	intree->SetBranchAddress("thetalab_hit1", &theta[0]);
	intree->SetBranchAddress("philab_hit1", &phi[0]);

	intree->SetBranchAddress("SabreRingEnergy_hit2", &E[1]);
	intree->SetBranchAddress("thetalab_hit2", &theta[1]);
	intree->SetBranchAddress("philab_hit2", &phi[1]);

	intree->SetBranchAddress("SabreRingEnergy_hit3", &E[2]);
	intree->SetBranchAddress("thetalab_hit3", &theta[2]);
	intree->SetBranchAddress("philab_hit3", &phi[2]);

	long numentries = intree->GetEntries();

	TFile *outfile = new TFile(out_str.c_str(), "RECREATE");
	TDirectory *sliceDir = outfile->mkdir("slices");

	outfile->cd();

	TH1D *hProtonPicks = new TH1D("hProtonPicks", "Hit Index Assigned to Proton", 3, -0.5, 2.5);
	hProtonPicks->SetDirectory(outfile);

	TH2D *hDalitzInvMass = new TH2D("hDalitzInvMass", "M^{2}_{p+#alpha} vs M^{2}_{#alpha+#alpha};M^{2}_{#alpha+#alpha};M^{2}_{p+#alpha}",
									400, 55.57e6, 55.69e6,
									400, 21.76e6, 21.84e6);
	hDalitzInvMass->SetDirectory(outfile);

	TH2D *hDalitzInvMass_pa1_pa2 = new TH2D("hDalitzInvMass_pa1_pa2", "M^{2}_{p#alpha_{1}} vs M^{2}_{p#alpha_{2}};M^{2}_{p#alpha_{2}};M^{2}_{p#alpha_{1}}",
									400, 21.76e6, 21.84e6,
									400, 21.76e6, 21.84e6);
	hDalitzInvMass_pa1_pa2->SetDirectory(outfile);

	TH2D *hDalitzInvMass_a1 = new TH2D("hDalitzInvMass_a1", "M^{2}_{p+#alpha_{1}} vs M^{2}_{#alpha+#alpha};M^{2}_{#alpha+#alpha};M^{2}_{p+#alpha_{1}}",
									400, 55.57e6, 55.69e6,
									400, 21.76e6, 21.84e6);
	hDalitzInvMass_a1->SetDirectory(outfile);

	TH2D *hDalitzInvMass_a2 = new TH2D("hDalitzInvMass_a2", "M^{2}_{p+#alpha_{2}} vs M^{2}_{#alpha+#alpha};M^{2}_{#alpha+#alpha};M^{2}_{p+#alpha_{2}}",
									400, 55.57e6, 55.69e6,
									400, 21.76e6, 21.84e6);
	hDalitzInvMass_a2->SetDirectory(outfile);

	TH3D *hDalitzSlices = new TH3D("hDalitzSlices", "hDalitzSlices;M^{2}_{#alpha+#alpha};M^{2}_{p+#alpha};Ex", 
									400, 55.57e6, 55.69e6,
									400, 21.76e6, 21.84e6,
									70, 0, 7);

	TH1D *hCosThetaH = new TH1D("hCosThetaH", "Cos(Helicity Angle) Distribution, #alpha#alpha intermediate;cos(#theta^{h}_{#alpha})", 100, -1., 1.);
	hCosThetaH->SetDirectory(outfile);
	
	TH1D *hThetaH = new TH1D("hThetaH", "Helicity Angle Distribution, #alpha#alpha intermediate;#theta^{h}_{#alpha} [deg]",90,0.,180.);
	hThetaH->SetDirectory(outfile);

	TH2D *hCosThetaH_vs_M2aa = new TH2D("hCosThetaH_vs_M2aa", "Cos(Helicty Angle) vs M^{2}_{#alpha#alpha};M^{2}_{#alpha#alpha};cos(#theta^{h}_{#alpha})", 400, 55.57e6, 55.67e6, 100, -1., 1.);
	hCosThetaH_vs_M2aa->SetDirectory(outfile);

	//lambda to calculate dalitz boundary as function of excitation energy
	auto MakeDalitzBoundary = [&](double W, int sliceindex, double sliceEMin, double sliceEMax, int npoints=500) -> TGraph*
	{
		// W = invariant mass of parent resonance, W = E_tot = M(9B_gs) + AVGEX(sliceindex)
		// (take the average Ex to be the middle value between the Ex min and max for the given slice)

		//Plot axes:
		// x = M^2_{aa} = M^2{23} = s_aa = s_23
		// y = M^2_{pa} = M^2{12} = s_pa = s_12

		const double xmin = 4.*mass_a*mass_a;			// (2m_a)^2
		const double xmax = std::pow(W - mass_p, 2);	// (W - m_p)^2

		std::vector<double> x;
		std::vector<double> y;

		x.reserve(2*npoints);
		y.reserve(2*npoints);

		//upper branch: ymax(x)
		for(int j=0; j<npoints; j++){
			const double frac = static_cast<double>(j)/(npoints-1);
			const double s_aa = xmin + frac*(xmax-xmin);

			const double lambda_aa = Kallen(s_aa, mass_a*mass_a, mass_a*mass_a);
			const double lambda_W = Kallen(W*W, s_aa, mass_p*mass_p);

			const double radical = std::sqrt(std::max(0., lambda_aa*lambda_W));

			const double center = mass_p*mass_p + mass_a*mass_a + ((W*W - mass_p*mass_p - s_aa)*s_aa)/(2.*s_aa);

			const double yPlus = center + radical/(2.0*s_aa);

			x.push_back(s_aa);
			y.push_back(yPlus);
		}

		//loewr branch: ymin(x)
		for(int j=npoints-1; j>=0; j--){
			const double frac = static_cast<double>(j)/(npoints-1);
			const double s_aa = xmin + frac*(xmax - xmin);

			const double lambda_aa = Kallen(s_aa, mass_a*mass_a, mass_a*mass_a);
			const double lambda_W = Kallen(W*W, s_aa, mass_p*mass_p);

			const double radical = std::sqrt(std::max(0., lambda_aa*lambda_W));

			const double center = mass_p*mass_p + mass_a*mass_a + ((W*W - mass_p*mass_p - s_aa)*s_aa)/(2.*s_aa);

			const double yMinus = center - radical/(2.*s_aa);

			x.push_back(s_aa);
			y.push_back(yMinus);
		}

		TGraph* graph = new TGraph(static_cast<int>(x.size()), x.data(), y.data());

		graph->SetName(Form("gDalitzBoundary_%02d", sliceindex));
		graph->SetTitle(Form("Dalitz Boundary, E_{x}=%.2f-%.2f MeV;M^{2}_{#alpha#alpha};M^{2}_{p#alpha}",sliceEMin,sliceEMax));
		graph->SetLineColor(kRed+1);
		graph->SetLineWidth(2);
		graph->SetLineStyle(1);
		graph->SetFillStyle(0);

		return graph;
	};

	//prep vector of Dalitz slices here:
	double eMin=0.;
	double eMax=7.;
	double eStep=0.1;
	int nSlices = static_cast<int>((eMax-eMin)/eStep);
	std::vector<TH2D*> vDalitz(nSlices, nullptr);
	std::vector<TGraph*> vDalitzBoundary(nSlices, nullptr);

	for(int i=0; i<nSlices; i++){
		double currentEMin = eMin + i*eStep;
		double currentEMax = eMin + (i+1)*eStep;
		double currentECenter = 0.5*(currentEMin+currentEMax);

		TString name = Form("hDalitz_%d_%.1f_%.1f", i, currentEMin, currentEMax);
		TString title = Form("M^{2}_{p+#alpha} vs M^{2}_{#alpha+#alpha} [%.1f - %.1f MeV];M^{2}_{#alpha+#alpha};M^{2}_{p+#alpha}", currentEMin, currentEMax);

		vDalitz[i] = new TH2D(name.Data(), title.Data(),
							  200, 55.57e6, 55.69e6,
							  200, 21.76e6, 21.84e6);
		vDalitz[i]->SetDirectory(sliceDir);

		const double W = massgs_9B + currentECenter;

		vDalitzBoundary[i] = MakeDalitzBoundary(W, i, currentEMin, currentEMax);

	}

	//std::cout << "Dalitz Plots set!" << std::endl;

	TH2D *hDalitzEx = new TH2D("hDalitzEx", "Ex(^{5}Li) vs Ex(^{8}Be);Ex(^{8}Be);Ex(^{5}Li)", 100, 0, 2, 100, 0, 2);
	hDalitzEx->SetDirectory(outfile);

	TH2D *hDalitzEx_a1 = new TH2D("hDalitzEx_a1", "Ex(^{5}Li = p+#alpha_{1}) vs Ex(^{8}Be);Ex(^{8}Be);Ex(^{5}Li = p+#alpha_{1})", 100, 0, 2, 100, 0, 2);
	hDalitzEx_a1->SetDirectory(outfile);

	TH2D *hDalitzEx_a2 = new TH2D("hDalitzEx_a2", "Ex(^{5}Li = p+#alpha_{2}) vs Ex(^{8}Be);Ex(^{8}Be);Ex(^{5}Li = p+#alpha_{2})", 100, 0, 2, 100, 0, 2);
	hDalitzEx_a2->SetDirectory(outfile);

	TH1D *hRecoilEx_8BegsGated = new TH1D("hRecoilEx_8BegsGated", "Recoil Ex (^{8}Be_{gs} cut)", 100, 0, 10);
	TH1D *hRecoilEx_5LigsGated = new TH1D("hRecoilEx_5LigsGated", "Recoil Ex (^{5}Li_{gs} cut)", 100, 0, 10);

	TH2D *hRecoilExSPS_vs_RecoilExSABRE = new TH2D("hRecoilExSPS_vs_RecoilExSABRE", "Recoil Ex SPS vs Recoil Ex SABRE;SABRE;SPS", 100, 0, 10, 100, 0, 10);
	TH2D *hRecoilExSPS_vs_RecoilExSABRE_8BegsGated = new TH2D("hRecoilExSPS_vs_RecoilExSABRE_8BegsGated", "Recoil Ex SPS vs Recoil Ex SABRE (8Begs Gated);SABRE;SPS", 100, 0, 10, 100, 0, 10);
	TH2D *hRecoilExSPS_vs_RecoilExSABRE_5LigsGated = new TH2D("hRecoilExSPS_vs_RecoilExSABRE_5LigsGated", "Recoil Ex SPS vs Recoil Ex SABRE (5Ligs Gated);SABRE;SPS", 100, 0, 10, 100, 0, 10);

	int lsuPurple = TColor::GetColor("#461D7C");
	int lsuGold   = TColor::GetColor("#FDD023");

	TGraph *gDalitzScatter_alpha1 = new TGraph();
	gDalitzScatter_alpha1->SetName("alpha1");
	//gDalitzScatter_alpha1->SetDirectory(outfile);
	gDalitzScatter_alpha1->SetMarkerStyle(1);
	gDalitzScatter_alpha1->SetMarkerColor(lsuPurple);

	TGraph *gDalitzScatter_alpha2 = new TGraph();
	gDalitzScatter_alpha2->SetName("alpha2");
	//gDalitzScatter_alpha2->SetDirectory(outfile);
	gDalitzScatter_alpha2->SetMarkerStyle(1);
	gDalitzScatter_alpha2->SetMarkerColor(lsuGold);

	PID_Mult3 pidSolver;
	pidSolver.SetHypothesis(hypothesis);
	pidSolver.SetResolution(0.05, 1.0, 1.0);
	pidSolver.SetSPSResolution(0.015, 0.5, 0.5);
	pidSolver.SetChi2Cut(10.);
	pidSolver.InitDiagnostics(outfile);

	TTree *outtree = new TTree("PID_Mult3","PID_Mult3");
	outtree->SetDirectory(outfile);

	int bestPermIndex;
	double bestChi2;
	bool passesCut;
	int proton_hit_index, alpha_hit_index1, alpha_hit_index2;//alpha_hit_index 1/2 does NOT necessarily refer to alpha1/alpha2 (we cannot tell these apart yet)

	TLorentzVector proton, alpha1, alpha2, recoil, intermediate;//again, alpha1/alpha2 are NOT necessarily the first/second alpha if sequential decay!
	double residual_px, residual_py, residual_pz, residual_pmag;

	double ExSPS, recoilEx, m2aa, m2pa1, m2pa2;
	double cosThetaH_a1, cosThetaH_a2;
	double thetaH_a1_deg, thetaH_a2_deg;

	outtree->Branch("bestPermIndex", &bestPermIndex, "bestPermIndex/I");
	outtree->Branch("bestChi2", &bestChi2, "bestChi2/D");
	outtree->Branch("passesCut", &passesCut, "passesCut/O");

	outtree->Branch("protonHitIndex", &proton_hit_index, "protonHitIndex/I");
	outtree->Branch("alphaHitIndex1", &alpha_hit_index1, "alphaHitIndex1/I");
	outtree->Branch("alphaHitIndex2", &alpha_hit_index2, "alphaHitIndex2/I");

	// Reconstructed 4-vectors
	outtree->Branch("P4_proton", &proton);
	outtree->Branch("P4_alpha1", &alpha1);
	outtree->Branch("P4_alpha2", &alpha2);
	outtree->Branch("P4_recoil", &recoil); // Sum of (p + a1 + a2)

	outtree->Branch("m2_aa", &m2aa);
	outtree->Branch("m2_pa1", &m2pa1);
	outtree->Branch("m2_pa2", &m2pa2);

	outtree->Branch("ExSPS", &ExSPS);
	outtree->Branch("RecEx", &recoilEx);

	outtree->Branch("cosThetaH_a1", &cosThetaH_a1, "cosThetaH_a1/D");
	outtree->Branch("cosThetaH_a2", &cosThetaH_a2, "cosThetaH_a2/D");
	outtree->Branch("thetaH_a1_deg", &thetaH_a1_deg, "thetaH_a1_deg/D");
	outtree->Branch("thetaH_a2_deg", &thetaH_a2_deg, "thetaH_a2_deg/D");

	// Residual momentum
	outtree->Branch("residual_px", &residual_px, "residual_px/D");
	outtree->Branch("residual_py", &residual_py, "residual_py/D");
	outtree->Branch("residual_pz", &residual_pz, "residual_pz/D");
	outtree->Branch("residual_Pmag", &residual_pmag, "residual_Pmag/D");

	for(long i=0; i<numentries; i++){
		//skip if Ex < 1.7:
		// if(Ex < 1.7){
		// 	continue;
		// }

		intree->GetEntry(i);

		PIDResult_Mult3 res = pidSolver.EvaluateEvent(E, theta, phi, SPSE, SPSTheta, SPSPhi);

		ExSPS = Ex;

		bestPermIndex = res.bestChi2Index;
		bestChi2 = res.bestChi2;
		passesCut = res.passesCut;

		//std::cout << "bestPermIndex = " << bestPermIndex << "\tbestChi2 = " << bestChi2 << "\npassesCut = " << passesCut << "\n";
		double proton_mass, alpha1_mass, alpha2_mass;
		if(simchan.EqualTo("paa")){
			//mass hypothesis: 0=p, 1=a, 2=a
			proton_hit_index = res.hit_indices[0];
			alpha_hit_index1 = res.hit_indices[1];
			alpha_hit_index2 = res.hit_indices[2];
			proton_mass = hypothesis.final_masses[0];
			alpha1_mass = hypothesis.final_masses[1];
			alpha2_mass = hypothesis.final_masses[2];
		} else if(simchan.EqualTo("apa")){
			//mass hypothesis: 0=a, 1=p, 2=a
			proton_hit_index = res.hit_indices[1];
			alpha_hit_index1 = res.hit_indices[0];
			alpha_hit_index2 = res.hit_indices[2];
			proton_mass = hypothesis.final_masses[1];
			alpha1_mass = hypothesis.final_masses[0];
			alpha2_mass = hypothesis.final_masses[2];
		}


		residual_px = res.missing_px;
		residual_py = res.missing_py;
		residual_pz = res.missing_pz;
		residual_pmag = res.missing_Pmag;

		if(bestPermIndex >= 0){
			auto buildP4 = [](double E, double theta, double phi, double m){
				double p = std::sqrt(E*(E+2.*m));
				double rad_th = theta*M_PI/180.;
				double rad_ph = phi*M_PI/180.;
				return TLorentzVector(
						p*std::sin(rad_th)*std::cos(rad_ph),
						p*std::sin(rad_th)*std::sin(rad_ph),
						p*std::cos(rad_th),
						E+m
					);
			};

			hProtonPicks->Fill(proton_hit_index);
			proton = buildP4(E[proton_hit_index], theta[proton_hit_index], phi[proton_hit_index], proton_mass);
			alpha1 = buildP4(E[alpha_hit_index1], theta[alpha_hit_index1], phi[alpha_hit_index1], alpha1_mass);
			alpha2 = buildP4(E[alpha_hit_index2], theta[alpha_hit_index2], phi[alpha_hit_index2], alpha2_mass);
			recoil = proton + alpha1 + alpha2;

			//get helicty angle here:
			//	parent frame: 			rest frame of recoil (recoil = p + alpha1 + alpha2)
			//	intermediate: 			alpha1 + alpha2
			//
			//calculation follows "General Properties of Three-body Decays" by Curtis Meyer, Carnegie Mellon University
			//the paper uses the direction of the lorentz boost that takes parent CM frame -> a1+a2 rest frame.
			//Thus, we can say the reference direction is  -beta_aa_in_parent_CM
			TLorentzVector protonCM = proton;
			TLorentzVector alpha1CM = alpha1;
			TLorentzVector alpha2CM = alpha2;

			TVector3 betaLabToParentCM = -recoil.BoostVector();
			protonCM.Boost(betaLabToParentCM);
			alpha1CM.Boost(betaLabToParentCM);
			alpha2CM.Boost(betaLabToParentCM);

			TLorentzVector intermediateCM = alpha1CM + alpha2CM;
			TVector3 betaCMtoIntermediateCM = -intermediateCM.BoostVector();

			cosThetaH_a1 = -666.;
			cosThetaH_a2 = -666.;
			thetaH_a1_deg = -666.;
			thetaH_a2_deg = -666.;


			if(betaCMtoIntermediateCM.Mag() > 1e-12 && alpha1CM.P() > 1e-12 && alpha2CM.P() > 1e-12 ){
				TVector3 helicityAxis = betaCMtoIntermediateCM.Unit();
				TLorentzVector alpha1AA = alpha1CM;
				TLorentzVector alpha2AA = alpha2CM;

				alpha1AA.Boost(betaCMtoIntermediateCM);
				alpha2AA.Boost(betaCMtoIntermediateCM);

				cosThetaH_a1 = std::max(-1.,std::min(1., alpha1CM.Vect().Unit().Dot(helicityAxis)));
				cosThetaH_a2 = std::max(-1.,std::min(1., alpha1CM.Vect().Unit().Dot(helicityAxis)));

				thetaH_a1_deg = std::acos(cosThetaH_a1)*RADDEG;
				thetaH_a2_deg = std::acos(cosThetaH_a2)*RADDEG;
			}

			//now we can do invariant mass stuff here, but remember we must double fill any p+a (p+a1 and p+a2 since we cannot tell a1 from a2)

			double m2_aa = (alpha1+alpha2).M2();
			double m2_pa1 = (proton+alpha1).M2();
			double m2_pa2 = (proton+alpha2).M2();

			m2aa = m2_aa;
			m2pa1 = m2_pa1;
			m2pa2 = m2_pa2;
			//if(Ex > 1.7){
				hDalitzInvMass->Fill(m2_aa, m2_pa1);//x = a+a, y = p+a
				hDalitzInvMass_a1->Fill(m2_aa, m2_pa1);//x = a+a, y = p+a1

				hDalitzInvMass->Fill(m2_aa, m2_pa2);//x = a+a, y = p+a
				hDalitzInvMass_a2->Fill(m2_aa, m2_pa2);//x = a+a, y = p+a2

				hDalitzSlices->Fill(m2_aa, m2_pa1, ExSPS);
				hDalitzSlices->Fill(m2_aa, m2_pa2, ExSPS);

				hDalitzInvMass_pa1_pa2->Fill(m2_pa2, m2_pa1);

				gDalitzScatter_alpha1->SetPoint(gDalitzScatter_alpha1->GetN(), m2_aa, m2_pa1);
				gDalitzScatter_alpha2->SetPoint(gDalitzScatter_alpha2->GetN(), m2_aa, m2_pa2);

				hDalitzEx->Fill(std::sqrt(m2_aa) - massgs_8Be, std::sqrt(m2_pa1) - massgs_5Li);
				hDalitzEx_a1->Fill(std::sqrt(m2_aa) - massgs_8Be, std::sqrt(m2_pa1) - massgs_5Li);

				hDalitzEx->Fill(std::sqrt(m2_aa) - massgs_8Be, std::sqrt(m2_pa2) - massgs_5Li);
				hDalitzEx_a2->Fill(std::sqrt(m2_aa) - massgs_8Be, std::sqrt(m2_pa2) - massgs_5Li);

				hCosThetaH->Fill(cosThetaH_a1);
				hCosThetaH->Fill(cosThetaH_a2);

				hThetaH->Fill(thetaH_a1_deg);
				hThetaH->Fill(thetaH_a2_deg);

				hCosThetaH_vs_M2aa->Fill(m2_aa, cosThetaH_a1);
				hCosThetaH_vs_M2aa->Fill(m2_aa, cosThetaH_a2);
			//}

			int sliceIndex = static_cast<int>((Ex-eMin)/eStep);
			if(sliceIndex >= 0 && sliceIndex < nSlices){
				vDalitz[sliceIndex]->Fill(m2_aa, m2_pa1);
				vDalitz[sliceIndex]->Fill(m2_aa, m2_pa2);
			}

			recoilEx = recoil.M() - massgs_9B;
			hRecoilExSPS_vs_RecoilExSABRE->Fill(recoilEx, Ex);
			if(std::sqrt(m2_aa) - massgs_8Be > 0 && std::sqrt(m2_aa) - massgs_8Be < 0.5){
				hRecoilEx_8BegsGated->Fill(recoilEx);
				hRecoilExSPS_vs_RecoilExSABRE_8BegsGated->Fill(recoilEx, Ex);
				//std::cout << "Filled hRecoilEx_8BegsGated" << std::endl;
			} else if(std::sqrt(m2_pa1) - massgs_5Li > 0 && std::sqrt(m2_pa1) - massgs_5Li < 1){
				hRecoilEx_5LigsGated->Fill(recoilEx);
				hRecoilExSPS_vs_RecoilExSABRE_5LigsGated->Fill(recoilEx, Ex);
				//std::cout << "Filled hRecoilEx_5LigsGated" << std::endl;
			} else if(std::sqrt(m2_pa2) - massgs_5Li > 0 && std::sqrt(m2_pa2) - massgs_5Li < 1){
				hRecoilEx_5LigsGated->Fill(recoilEx);
				hRecoilExSPS_vs_RecoilExSABRE_5LigsGated->Fill(recoilEx, Ex);
				//std::cout << "Filled hRecoilEx_5LigsGated" << std::endl;
			}

			outtree->Fill();

		}// else {
		// 	m2aa = -666.;
		// 	m2pa1 = -666.;
		// 	m2pa2 = -666.;
		// 	proton.SetPxPyPzE(0.,0.,0.,0.);
		// 	alpha1.SetPxPyPzE(0.,0.,0.,0.);
		// 	alpha2.SetPxPyPzE(0.,0.,0.,0.);
		// 	recoil.SetPxPyPzE(0.,0.,0.,0.);
		// }

		//outtree->Fill();

		if(i % 10000 == 0){
			std::cout << "Processed " << i << " events..." << std::endl;
		}
	}


	infile->Close();

	outfile->cd();
	gDalitzScatter_alpha1->Write();
	gDalitzScatter_alpha2->Write();
	sliceDir->cd();
	for(int i=0; i<nSlices; i++) if(vDalitzBoundary[i]) vDalitzBoundary[i]->Write();
	outfile->cd();
	outfile->Write();
	outfile->Close();
	delete outfile;

	std::cout << "Finished! Processed " << numentries << " events. Output stored in " << out_str.c_str() << std::endl;
}

void B10ha_SABREPID_Mult2(const char* input_filename){
	std::string s = input_filename;
	size_t last_dot = s.find_last_of(".");
	std::string stem = (last_dot == std::string::npos ? s : s.substr(0, last_dot));
	std::string out_str = stem + "_SABREPID_Mult2.root";

	TMassTable fMassTable;
	fMassTable.Init("/home/zachpurcell/masstable/masstable.dat");

	double massgs_5Li = fMassTable.GetNuclearMassMeV("Li", 5);
	double massgs_8Be = fMassTable.GetNuclearMassMeV("Be", 8);
	double massgs_9B  = fMassTable.GetNuclearMassMeV("B", 9);

	double mass_p = fMassTable.GetNuclearMassMeV("H",1);
	double mass_a = fMassTable.GetNuclearMassMeV("He",4);

	//hypothesis: final state = {p, alpha, alpha}
	//we expect 2 detected hits in SABRE and 1 reconstructed missing particle
	PIDHypothesis hypothesis;
	hypothesis.name = "paa_missing";
	hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
	hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
	hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
	hypothesis.beamEnergyMeV = 7.5;

	hypothesis.final_masses[0] = fMassTable.GetNuclearMassMeV("H",1);
	hypothesis.final_particles[0] = "p";
	hypothesis.final_masses[1] = fMassTable.GetNuclearMassMeV("He",4);
	hypothesis.final_particles[1] = "a";
	hypothesis.final_masses[2] = fMassTable.GetNuclearMassMeV("He",4);
	hypothesis.final_particles[2] = "a";

	TFile *infile = TFile::Open(input_filename, "READ");
	if(!infile || infile->IsZombie()){
		std::cerr << "Error: Cannot open input file " << input_filename << std::endl;
		return;
	}

	//input ttree for 2 detected hits:
	TTree *intree = (TTree*)infile->Get("mult2");
	if(!intree){
		std::cerr << "Error: Cannot get TTree 'mult2' from " << input_filename << std::endl;
		infile->Close();
		return;
	}

	double Ex, SPSE, SPSTheta, SPSPhi;
	intree->SetBranchAddress("ExE", &Ex);
	intree->SetBranchAddress("SPSEnergy", &SPSE);
	intree->SetBranchAddress("SPSTheta", &SPSTheta);
	intree->SetBranchAddress("SPSPhi", &SPSPhi);

	double E[2], theta[2], phi[2];
	intree->SetBranchAddress("SabreRingEnergy_hit1", &E[0]);
	intree->SetBranchAddress("thetalab_hit1", &theta[0]);
	intree->SetBranchAddress("philab_hit1", &phi[0]);

	intree->SetBranchAddress("SabreRingEnergy_hit2", &E[1]);
	intree->SetBranchAddress("thetalab_hit2", &theta[1]);
	intree->SetBranchAddress("philab_hit2", &phi[1]);

	long numentries = intree->GetEntries();

	TFile *outfile = new TFile(out_str.c_str(), "RECREATE");

	TDirectory *sliceDir = outfile->mkdir("slices");
	TDirectory *dalitzSlicesDir = sliceDir->mkdir("Dalitz");
	TDirectory *cataniaSlicesDir = sliceDir->mkdir("Catania");

	outfile->cd();

	TH1D *hAssignedSpeciesHit0 = new TH1D("hAssignedSpeciesHit0", "Species Assigned to Hit 0", 3, -0.5, 2.5);
	TH1D *hAssignedSpeciesHit1 = new TH1D("hAssignedSpeciesHit1", "Species Assigned to Hit 1", 3, -0.5, 2.5);
	TH1D *hMissingSpecies = new TH1D("hMissingSpecies", "Species Assigned as Missing", 3, -0.5, 2.5);

	TH2D *hDalitzInvMass = new TH2D("hDalitzInvMass", "M^{2}_{p+#alpha} vs M^{2}_{#alpha+#alpha};M^{2}_{#alpha+#alpha};M^{2}_{p+#alpha}",
									400, 55.57e6, 55.69e6,
									400, 21.76e6, 21.84e6);

	TH2D *hDalitzInvMass_pa1_pa2 = new TH2D("hDalitzInvMass_pa1_pa2", "M^{2}_{p#alpha_{1}} vs M^{2}_{p#alpha_{2}};M^{2}_{p#alpha_{2}};M^{2}_{p#alpha_{1}}",
									400, 21.76e6, 21.84e6,
									400, 21.76e6, 21.84e6);
	hDalitzInvMass_pa1_pa2->SetDirectory(outfile);

	TH3D *hDalitzSlices = new TH3D("hDalitzSlices", "hDalitzSlices;M^{2}_{#alpha+#alpha};M^{2}_{p+#alpha};Ex", 
									400, 55.57e6, 55.69e6,
									400, 21.76e6, 21.84e6,
									70, 0, 7);

	TH1D *hCosThetaH = new TH1D("hCosThetaH", "Cos(Helicity Angle) Distribution, #alpha#alpha intermediate;cos(#theta^{h}_{#alpha})", 100, -1., 1.);
	hCosThetaH->SetDirectory(outfile);
	
	TH1D *hThetaH = new TH1D("hThetaH", "Helicity Angle Distribution, #alpha#alpha intermediate;#theta^{h}_{#alpha} [deg]",90,0.,180.);
	hThetaH->SetDirectory(outfile);

	TH2D *hCosThetaH_vs_M2aa = new TH2D("hCosThetaH_vs_M2aa", "Cos(Helicty Angle) vs M^{2}_{#alpha#alpha};M^{2}_{#alpha#alpha};cos(#theta^{h}_{#alpha})", 400, 55.57e6, 55.67e6, 100, -1., 1.);
	hCosThetaH_vs_M2aa->SetDirectory(outfile);

	//lambda to calculate dalitz boundary as function of excitation energy
	auto MakeDalitzBoundary = [&](double W, int sliceindex, double sliceEMin, double sliceEMax, int npoints=500) -> TGraph*
	{
		// W = invariant mass of parent resonance, W = E_tot = M(9B_gs) + AVGEX(sliceindex)
		// (take the average Ex to be the middle value between the Ex min and max for the given slice)

		//Plot axes:
		// x = M^2_{aa} = M^2{23} = s_aa = s_23
		// y = M^2_{pa} = M^2{12} = s_pa = s_12

		const double xmin = 4.*mass_a*mass_a;			// (2m_a)^2
		const double xmax = std::pow(W - mass_p, 2);	// (W - m_p)^2

		std::vector<double> x;
		std::vector<double> y;

		x.reserve(2*npoints);
		y.reserve(2*npoints);

		//upper branch: ymax(x)
		for(int j=0; j<npoints; j++){
			const double frac = static_cast<double>(j)/(npoints-1);
			const double s_aa = xmin + frac*(xmax-xmin);

			const double lambda_aa = Kallen(s_aa, mass_a*mass_a, mass_a*mass_a);
			const double lambda_W = Kallen(W*W, s_aa, mass_p*mass_p);

			const double radical = std::sqrt(std::max(0., lambda_aa*lambda_W));

			const double center = mass_p*mass_p + mass_a*mass_a + ((W*W - mass_p*mass_p - s_aa)*s_aa)/(2.*s_aa);

			const double yPlus = center + radical/(2.0*s_aa);

			x.push_back(s_aa);
			y.push_back(yPlus);
		}

		//loewr branch: ymin(x)
		for(int j=npoints-1; j>=0; j--){
			const double frac = static_cast<double>(j)/(npoints-1);
			const double s_aa = xmin + frac*(xmax - xmin);

			const double lambda_aa = Kallen(s_aa, mass_a*mass_a, mass_a*mass_a);
			const double lambda_W = Kallen(W*W, s_aa, mass_p*mass_p);

			const double radical = std::sqrt(std::max(0., lambda_aa*lambda_W));

			const double center = mass_p*mass_p + mass_a*mass_a + ((W*W - mass_p*mass_p - s_aa)*s_aa)/(2.*s_aa);

			const double yMinus = center - radical/(2.*s_aa);

			x.push_back(s_aa);
			y.push_back(yMinus);
		}

		TGraph* graph = new TGraph(static_cast<int>(x.size()), x.data(), y.data());

		graph->SetName(Form("gDalitzBoundary_%02d", sliceindex));
		graph->SetTitle(Form("Dalitz Boundary, E_{x}=%.2f-%.2f MeV;M^{2}_{#alpha#alpha};M^{2}_{p#alpha}",sliceEMin,sliceEMax));
		graph->SetLineColor(kRed+1);
		graph->SetLineWidth(2);
		graph->SetLineStyle(1);
		graph->SetFillStyle(0);

		return graph;
	};

	//prep vectors of Dalitz, Catania slices here:
	double eMin=0.;
	double eMax=7.;
	double eStep=0.1;
	int nSlices = static_cast<int>((eMax-eMin)/eStep);
	std::vector<TH2D*> vDalitz(nSlices, nullptr);
	std::vector<TH2D*> vCatania(nSlices, nullptr);
	std::vector<TGraph*> vDalitzBoundary(nSlices, nullptr);

	for(int i=0; i<nSlices; i++){
		double currentEMin = eMin + i*eStep;
		double currentEMax = eMin + (i+1)*eStep;
		double currentECenter = 0.5*(currentEMin+currentEMax);

		TString name = Form("hDalitz_%d_%.1f_%.1f", i, currentEMin, currentEMax);
		TString title = Form("M^{2}_{p+#alpha} vs M^{2}_{#alpha+#alpha} [%.1f - %.1f MeV];M^{2}_{#alpha+#alpha};M^{2}_{p+#alpha}", currentEMin, currentEMax);

		vDalitz[i] = new TH2D(name.Data(), title.Data(),
							  200, 55.57e6, 55.69e6,
							  200, 21.76e6, 21.84e6);
		vDalitz[i]->SetDirectory(dalitzSlicesDir);

		name = Form("hCatania_%d_%.1f_%.1f", i, currentEMin, currentEMax);
		title = Form("Catania Plot (P_{missing}^{2}/(2m) vs E_{missing}-Q) [%.1f - %.1f MeV]", currentEMin, currentEMax);

		vCatania[i] = new TH2D(name.Data(), title.Data(),
							   50, 0, 10,
							   50, 0, 10);
		vCatania[i]->SetDirectory(cataniaSlicesDir);

		const double W = massgs_9B + currentECenter;

		vDalitzBoundary[i] = MakeDalitzBoundary(W, i, currentEMin, currentEMax);

	}


	TH2D *hDalitzEx = new TH2D("hDalitzEx", "Ex(^{5}Li) vs Ex(^{8}Be); Ex(^{8}Be); Ex(^{5}Li)", 200, 0, 8, 200, 0, 8);
	TH1D *hRecoilEx_8BegsGated = new TH1D("hRecoilEx_8BegsGated", "Ex(^{5}Li) vs Ex(^{8}Be) (^{8}Be_{gs} Gated); Ex(f^{8}Be); Ex(^{5}Li)", 200, 0, 8);
	TH1D *hRecoilEx_5LigsGated = new TH1D("hRecoilEx_5LigsGated", "Ex(^{5}Li) vs Ex(^{8}Be) (^{5}Li_{gs} Gated); Ex(f^{8}Be); Ex(^{5}Li)", 200, 0, 8);

	TH2D *hCatania = new TH2D("catania_plot", "Catania Plot (P_{missing}^{2}/(2m) vs E_{missing}-Q)", 100, 0, 10, 100, 0, 10);

	TH2D *hRecoilExSPS_vs_RecoilExSABRE = new TH2D("hRecoilExSPS_vs_RecoilExSABRE", "Recoil Ex SPS vs Recoil Ex SABRE; SABRE; SPS", 100, 0, 8, 100, 0, 8);
	TH2D *hRecoilExSPS_vs_RecoilExSABRE_8BegsGated = new TH2D("hRecoilExSPS_vs_RecoilExSABRE_8BegsGated", "Recoil Ex SPS vs Recoil Ex (^{8}Be_{gs} Gated);SABRE;SPS", 100, 0, 8, 100, 0, 8);
	TH2D *hRecoilExSPS_vs_RecoilExSABRE_5LigsGated = new TH2D("hRecoilExSPS_vs_RecoilExSABRE_5LigsGated", "Recoil Ex SPS vs Recoil Ex (^{5}Li_{gs} Gated);SABRE;SPS", 100, 0, 8, 100, 0, 8);

	PID_Mult2 pidSolver;
	pidSolver.SetHypothesis(hypothesis);
	pidSolver.SetResolution(0.05, 1.0, 1.0);//eventually, update this per run w/ pixel handler map
	pidSolver.SetSPSResolution(0.015, 0.5, 0.5); //eventuall, update this per run w/ pixel handler map
	pidSolver.SetChi2Cut(10.);
	pidSolver.InitDiagnostics(outfile);

	TTree *outtree = new TTree("PID_Mult2", "PID_Mult2");
	outtree->SetDirectory(outfile);

	int bestPermIndex;
	double bestChi2;
	bool passesCut;
	int hit0_species, hit1_species, missing_species;

	//stack objects for intermediate operations
	TLorentzVector P4_hit0, P4_hit1, P4_missing, recoil;

	//pointers to pass to TTree:Branch (ROOT requires this for TLorentzVector type)
	TLorentzVector *p4_0_ptr = &P4_hit0;
	TLorentzVector *p4_1_ptr = &P4_hit1;
	TLorentzVector *p4_miss_ptr = &P4_missing;
	TLorentzVector *p4_rec_ptr = &recoil;

	double m2_aa, m2_pa1, m2_pa2;
	double ExSPS, recoilEx;
	double cosThetaH_a1, cosThetaH_a2;
	double thetaH_a1_deg, thetaH_a2_deg;
	double catania_x, catania_y;

	outtree->Branch("bestPermIndex", &bestPermIndex, "bestPermIndex/I");
	outtree->Branch("bestChi2", &bestChi2, "bestChi2/D");
	outtree->Branch("passesCut", &passesCut, "passesCut/O");

	outtree->Branch("hit0species", &hit0_species, "hit0species/I");
	outtree->Branch("hit1species", &hit1_species, "hit1species/I");
	outtree->Branch("missingSpecies", &missing_species, "missingSpecies/I");

	outtree->Branch("P4_hit0", &p4_0_ptr);
	outtree->Branch("P4_hit1", &p4_1_ptr);
	outtree->Branch("P4_missing", &p4_miss_ptr);
	outtree->Branch("P4_recoil", &p4_rec_ptr);

	outtree->Branch("m2_aa", &m2_aa);
	outtree->Branch("m2_pa1", &m2_pa1);
	outtree->Branch("m2_pa2", &m2_pa2);

	outtree->Branch("ExSPS", &ExSPS);
	outtree->Branch("RecEx", &recoilEx);

	outtree->Branch("cosThetaH_a1", &cosThetaH_a1, "cosThetaH_a1/D");
	outtree->Branch("cosThetaH_a2", &cosThetaH_a2, "cosThetaH_a2/D");
	outtree->Branch("thetaH_a1_deg", &thetaH_a1_deg, "thetaH_a1_deg/D");
	outtree->Branch("thetaH_a2_deg", &thetaH_a2_deg, "thetaH_a2_deg/D");

	outtree->Branch("catania_x", &catania_x);
	outtree->Branch("catania_y", &catania_y);

	auto buildP4 = [](double E_kin, double th_deg, double ph_deg, double mass) {
		double p = std::sqrt(E_kin * (E_kin + 2.0 * mass));
		double rad_th = th_deg * DEGRAD;
		double rad_ph = ph_deg * DEGRAD;
		return TLorentzVector(
			p * std::sin(rad_th) * std::cos(rad_ph),
			p * std::sin(rad_th) * std::sin(rad_ph),
			p * std::cos(rad_th),
			E_kin + mass
		);
	};


	for(long i=0; i<numentries; i++){
		intree->GetEntry(i);

		//skip if Ex < 1.7:
		// if(Ex < 1.7){
		// 	continue;
		// }

		ExSPS = Ex;

		PIDResult_Mult2 res = pidSolver.EvaluateEvent(E, theta, phi, SPSE, SPSTheta, SPSPhi);

		bestPermIndex = res.bestChi2Index;
		bestChi2 = res.bestChi2;
		passesCut = true;//res.passesCut;

		hit0_species = res.hit_indices[0];
		hit1_species = res.hit_indices[1];
		missing_species = res.missing_species_index;

		if(bestPermIndex >= 0){
			hAssignedSpeciesHit0->Fill(hit0_species);
			hAssignedSpeciesHit1->Fill(hit1_species);
			hMissingSpecies->Fill(missing_species);

			P4_hit0 = buildP4(E[0], theta[0], phi[0], hypothesis.final_masses[hit0_species]);
			P4_hit1 = buildP4(E[1], theta[1], phi[1], hypothesis.final_masses[hit1_species]);

			P4_missing.SetPxPyPzE(res.missing_px, res.missing_py, res.missing_pz, res.missing_Etot);

			//determine recoil using objects on stack:
			recoil = P4_hit0 + P4_hit1 + P4_missing;

			TLorentzVector proton, alpha1, alpha2;

			if(hit0_species == 0){//hit0 is the proton
				proton = P4_hit0;
				alpha1 = P4_hit1;
				alpha2 = P4_missing;
			} else if(hit1_species == 0){//hit1 is the proton
				proton = P4_hit1;
				alpha1 = P4_hit0;
				alpha2 = P4_missing;
			} else {//missing particle is the proton
				proton = P4_missing;
				alpha1 = P4_hit0;
				alpha2 = P4_hit1;
			}

			int sliceIndex = static_cast<int>((Ex-eMin)/eStep);

			catania_x = (P4_missing.P() * P4_missing.P()) / (2*AMU_IN_MEV);
			catania_y = (hypothesis.beamEnergyMeV - E[0] - E[1]);// - SPSE);
			hCatania->Fill(catania_x, catania_y);

			//get helicty angle here:
			//	parent frame: 			rest frame of recoil (recoil = p + alpha1 + alpha2)
			//	intermediate: 			alpha1 + alpha2
			//
			//calculation follows "General Properties of Three-body Decays" by Curtis Meyer, Carnegie Mellon University
			//the paper uses the direction of the lorentz boost that takes parent CM frame -> a1+a2 rest frame.
			//Thus, we can say the reference direction is  -beta_aa_in_parent_CM
			TLorentzVector protonCM = proton;
			TLorentzVector alpha1CM = alpha1;
			TLorentzVector alpha2CM = alpha2;

			TVector3 betaLabToParentCM = -recoil.BoostVector();
			protonCM.Boost(betaLabToParentCM);
			alpha1CM.Boost(betaLabToParentCM);
			alpha2CM.Boost(betaLabToParentCM);

			TLorentzVector intermediateCM = alpha1CM + alpha2CM;
			TVector3 betaCMtoIntermediateCM = -intermediateCM.BoostVector();

			cosThetaH_a1 = -666.;
			cosThetaH_a2 = -666.;
			thetaH_a1_deg = -666.;
			thetaH_a2_deg = -666.;


			if(betaCMtoIntermediateCM.Mag() > 1e-12 && alpha1CM.P() > 1e-12 && alpha2CM.P() > 1e-12 ){
				TVector3 helicityAxis = betaCMtoIntermediateCM.Unit();
				TLorentzVector alpha1AA = alpha1CM;
				TLorentzVector alpha2AA = alpha2CM;

				alpha1AA.Boost(betaCMtoIntermediateCM);
				alpha2AA.Boost(betaCMtoIntermediateCM);

				cosThetaH_a1 = std::max(-1.,std::min(1., alpha1CM.Vect().Unit().Dot(helicityAxis)));
				cosThetaH_a2 = std::max(-1.,std::min(1., alpha1CM.Vect().Unit().Dot(helicityAxis)));

				thetaH_a1_deg = std::acos(cosThetaH_a1)*RADDEG;
				thetaH_a2_deg = std::acos(cosThetaH_a2)*RADDEG;
			}

			//invariant mass calculations:
			m2_aa = (alpha1+alpha2).M2();
			m2_pa1 = (proton+alpha1).M2();
			m2_pa2 = (proton+alpha2).M2();

			//double fill p+a combinations due to alpha indistinguishability
			//if(Ex>1.7){
				hDalitzInvMass->Fill(m2_aa, m2_pa1);
				hDalitzInvMass->Fill(m2_aa, m2_pa2);

				hDalitzSlices->Fill(m2_aa, m2_pa1, ExSPS);
				hDalitzSlices->Fill(m2_aa, m2_pa2, ExSPS);

				hDalitzInvMass_pa1_pa2->Fill(m2_pa2, m2_pa1);

			//}


			if(sliceIndex >= 0 && sliceIndex < nSlices){
				vDalitz[sliceIndex]->Fill(m2_aa, m2_pa1);
				vDalitz[sliceIndex]->Fill(m2_aa, m2_pa2);

				vCatania[sliceIndex]->Fill(catania_x, catania_y);
			}



			double ex_8Be = std::sqrt(m2_aa) - massgs_8Be;
			double ex_5Li1 = std::sqrt(m2_pa1) - massgs_5Li;
			double ex_5Li2 = std::sqrt(m2_pa2) - massgs_5Li;
			//double fill p+a combinations due to alpha indistinguishability
			//if(Ex>1.7){	
				hDalitzEx->Fill(ex_8Be, ex_5Li1);
				hDalitzEx->Fill(ex_8Be, ex_5Li2);

				hCosThetaH->Fill(cosThetaH_a1);
				hCosThetaH->Fill(cosThetaH_a2);

				hThetaH->Fill(thetaH_a1_deg);
				hThetaH->Fill(thetaH_a2_deg);

				hCosThetaH_vs_M2aa->Fill(m2_aa, cosThetaH_a1);
				hCosThetaH_vs_M2aa->Fill(m2_aa, cosThetaH_a2);
			//}

			recoilEx = recoil.M() - massgs_9B;
			hRecoilExSPS_vs_RecoilExSABRE->Fill(recoilEx, Ex);

			if(ex_8Be > 0. && ex_8Be < 0.5){
				hRecoilEx_8BegsGated->Fill(recoilEx);
				hRecoilExSPS_vs_RecoilExSABRE_8BegsGated->Fill(recoilEx, Ex);
			} else if((ex_5Li1 > 0. && ex_5Li1 < 1.) || (ex_5Li2 > 0. && ex_5Li2 < 1.)){
				hRecoilEx_5LigsGated->Fill(recoilEx);
				hRecoilExSPS_vs_RecoilExSABRE_5LigsGated->Fill(recoilEx, Ex);
			}
			outtree->Fill();
		}// else {
		// 	m2_aa = -666.;
		// 	m2_pa1 = -666.;
		// 	m2_pa2 = -666.;
		// 	P4_hit0.SetPxPyPzE(0., 0., 0., 0.);
		// 	P4_hit1.SetPxPyPzE(0., 0., 0., 0.);
		// 	P4_missing.SetPxPyPzE(0., 0., 0., 0.);
		// 	recoil.SetPxPyPzE(0., 0., 0., 0.);
		// }

		//outtree->Fill();

		if(i % 10000 == 0){
			std::cout << "Processed " << i << " events..." << std::endl;
		}
	}
	
	// outfile->cd();
	// outfile->Write();
	// outfile->Close();
	// infile->Close();
	// delete infile;

	infile->Close();
	dalitzSlicesDir->cd();
	for(int i=0; i<nSlices; i++) if(vDalitzBoundary[i]) vDalitzBoundary[i]->Write();
	outfile->cd();
	outfile->Write();
	outfile->Close();
	delete outfile;

	std::cout << "Finished! Processed " << numentries << " events. Output stored in " << out_str << std::endl;
}

//------------------------------DATA BELOW-------------------------------------
//commented below function until rewritten for updated TDirectory argument vs string filename 08/05/2026
// void B10ha_3par_exp_aboveAlphaThresh(const char* input_filename, const char* cutlist_p8Be_filename, const char* cutlist_a5Li_filename, bool updateRecoilEx = true, bool updateIntermediateEx = true){

// 	std::string s = input_filename;
// 	size_t last_dot = s.find_last_of(".");
// 	std::string stem = (last_dot == std::string::npos) ? s : s.substr(0, last_dot);

// 	std::string p8Be_str = stem + "_aboveAlphaThreshAnalyzed8Be.root";
// 	std::string a5Li_str = stem + "_aboveAlphaThreshAnalyzed5Li.root";

// 	const char* p8Be_output_filename = p8Be_str.c_str();
// 	const char* a5Li_output_filename = a5Li_str.c_str();

// 	TFile *infile = new TFile(input_filename, "READ");
// 	if(!infile || infile->IsZombie()){
// 		std::cerr << "Input file is bad: " << input_filename << std::endl;
// 		return;
// 	}

// 	TTree *intree = (TTree*)infile->Get("mult3");
// 	if(!intree){
// 		std::cerr << "Could not get TTree 'mult3' from " << input_filename << std::endl;
// 		return;
// 	}

// 	long numentries = intree->GetEntries();

// 	TMassTable fMassTable;
// 	fMassTable.Init("/home/zachpurcell/masstable/masstable.dat");

// 	Hypothesis4 b9_p8Be_hypothesis, b9_a5Li_hypothesis;

// 	b9_p8Be_hypothesis.name = "B10ha_8BeHypothesis";
// 	b9_p8Be_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
// 	b9_p8Be_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
// 	b9_p8Be_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_p8Be_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("B",9);
// 	b9_p8Be_hypothesis.mass_intermediate = fMassTable.GetNuclearMassMeV("Be",8);
// 	b9_p8Be_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("H",1);
// 	b9_p8Be_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_p8Be_hypothesis.masses[2] = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_p8Be_hypothesis.beamEnergyMeV = 7.5;


// 	b9_a5Li_hypothesis.name = "B10ha_5LiHypothesis";
// 	b9_a5Li_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
// 	b9_a5Li_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
// 	b9_a5Li_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_a5Li_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("B",9);
// 	b9_a5Li_hypothesis.mass_intermediate = fMassTable.GetNuclearMassMeV("Li",5);
// 	b9_a5Li_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_a5Li_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("H",1);
// 	b9_a5Li_hypothesis.masses[2] = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_a5Li_hypothesis.beamEnergyMeV = 7.5;


// 	InvMass_Mult3 b9_p8Be_analysis, b9_a5Li_analysis;

// 	b9_p8Be_analysis.Init(p8Be_output_filename);
// 	b9_p8Be_analysis.SetHypothesis(b9_p8Be_hypothesis);
// 	CutHandler& cuthandler = b9_p8Be_analysis.GetCutHandler();
// 	if(!cuthandler.LoadCutsFromConfig(cutlist_p8Be_filename)){
// 		std::cerr << "Warning: could not load at least one cut from " << cutlist_p8Be_filename << "!\n";
// 	}

// 	//test by printing cuts here:
// 	cuthandler.PrintCuts();

// 	b9_a5Li_analysis.Init(a5Li_output_filename);
// 	b9_a5Li_analysis.SetHypothesis(b9_a5Li_hypothesis);
// 	cuthandler = b9_a5Li_analysis.GetCutHandler();
// 	if(!cuthandler.LoadCutsFromConfig(cutlist_a5Li_filename)){
// 		std::cerr << "Warning: could not load at least one cut from " << cutlist_a5Li_filename << "!\n";
// 	}

// 	//test by printing cuts here:
// 	cuthandler.PrintCuts();


// 	double Ex, SPSE, SPSTheta, SPSPhi;
// 	intree->SetBranchAddress("ExE", &Ex);
// 	intree->SetBranchAddress("SPSEnergy", &SPSE);
// 	intree->SetBranchAddress("SPSTheta", &SPSTheta);
// 	intree->SetBranchAddress("SPSPhi", &SPSPhi);

// 	double E[3], theta[3], phi[3];
// 	intree->SetBranchAddress("SabreRingEnergy_hit1", &E[0]);
// 	intree->SetBranchAddress("thetalab_hit1", &theta[0]);
// 	intree->SetBranchAddress("philab_hit1", &phi[0]);

// 	intree->SetBranchAddress("SabreRingEnergy_hit2", &E[1]);
// 	intree->SetBranchAddress("thetalab_hit2", &theta[1]);
// 	intree->SetBranchAddress("philab_hit2", &phi[1]);

// 	intree->SetBranchAddress("SabreRingEnergy_hit3", &E[2]);
// 	intree->SetBranchAddress("thetalab_hit3", &theta[2]);
// 	intree->SetBranchAddress("philab_hit3", &phi[2]);

// 	std::cout << "Starting analysis on " << numentries << " entries..." << std::endl;
// 	for(long i=0; i<numentries; i++){

// 		intree->GetEntry(i);

// 		if(updateRecoilEx){
// 			b9_p8Be_analysis.SetRecoilEx(Ex);
// 			b9_a5Li_analysis.SetRecoilEx(Ex);
// 			//std::cout << "Ex = " << Ex << std::endl;
// 		}

// 		if(Ex >= 1.7){//only look at events we suspect are energetically capable of decaying via p+8Be OR a+5Li
// 			b9_p8Be_analysis.AnalyzeEvent(E, theta, phi, SPSE, SPSTheta, SPSPhi, Ex, updateIntermediateEx);
// 			b9_p8Be_analysis.FillEventHistograms(Ex);
// 			int numpasses_p8Be = b9_p8Be_analysis.CountPermPasses();
// 			b9_p8Be_analysis.FillPermCounter();
// 			b9_p8Be_analysis.FillSortedHisto(Ex);
// 			b9_p8Be_analysis.FillSABRESumEVsSPS_Ex(Ex, E[0]+E[1]+E[2]);
// 			b9_p8Be_analysis.FillTree();

// 			b9_a5Li_analysis.AnalyzeEvent(E, theta, phi, SPSE, SPSTheta, SPSPhi, Ex, updateIntermediateEx);
// 			b9_a5Li_analysis.FillEventHistograms(Ex);
// 			int numpasses_a5Li = b9_a5Li_analysis.CountPermPasses();
// 			b9_a5Li_analysis.FillPermCounter();
// 			b9_a5Li_analysis.FillSortedHisto(Ex);
// 			b9_a5Li_analysis.FillSABRESumEVsSPS_Ex(Ex, E[0]+E[1]+E[2]);
// 			b9_a5Li_analysis.FillTree();
// 			//std::cout << "test" << std::endl;
// 		}

// 		if(i % 1000 == 0){
// 			fprintf(stdout, "\rProgress: %.1f%% (%ld/%ld)",(float)i/numentries*100., i, numentries);
// 			fflush(stdout);
// 		}

// 	}

// 	b9_p8Be_analysis.CloseAndWrite();
// 	b9_a5Li_analysis.CloseAndWrite();

// 	infile->Close();

// 	std::cout << "\n\nAnalysis complete!\n" << std::endl;
// 	std::cout << "b9_p8Be output: " << p8Be_output_filename << std::endl;
// 	std::cout << "b9_a5Li output: " << a5Li_output_filename << std::endl;
// }
//commented below function until rewritten for updated TDirectory argument vs string filename 08/05/2026
// void B10ha_3par_exp_allEx(const char* input_filename, const char* cutlist_p8Be_filename, bool updateRecoilEx = true, bool updateIntermediateEx = true){

// 	std::string s = input_filename;
// 	size_t last_dot = s.find_last_of(".");
// 	std::string stem = (last_dot == std::string::npos) ? s : s.substr(0, last_dot);

// 	std::string p8Be_str = stem + "_allExAnalyzed8Be.root";
// 	// std::string a5Li_str = stem + "_analyzed5Li.root";

// 	const char* p8Be_output_filename = p8Be_str.c_str();
// 	//const char* a5Li_output_filename = a5Li_str.c_str();

// 	TFile *infile = new TFile(input_filename, "READ");
// 	if(!infile || infile->IsZombie()){
// 		std::cerr << "Input file is bad: " << input_filename << std::endl;
// 		return;
// 	}

// 	TTree *intree = (TTree*)infile->Get("mult3");
// 	if(!intree){
// 		std::cerr << "Could not get TTree 'mult3' from " << input_filename << std::endl;
// 		return;
// 	}

// 	long numentries = intree->GetEntries();

// 	TMassTable fMassTable;
// 	fMassTable.Init("/home/zachpurcell/masstable/masstable.dat");

// 	Hypothesis4 b9_p8Be_hypothesis;//, b9_a5Li_hypothesis;

// 	b9_p8Be_hypothesis.name = "B10ha_8BeHypothesis";
// 	b9_p8Be_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
// 	b9_p8Be_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
// 	b9_p8Be_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_p8Be_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("B",9);
// 	b9_p8Be_hypothesis.mass_intermediate = fMassTable.GetNuclearMassMeV("Be",8);
// 	b9_p8Be_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("H",1);
// 	b9_p8Be_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_p8Be_hypothesis.masses[2] = fMassTable.GetNuclearMassMeV("He",4);
// 	b9_p8Be_hypothesis.beamEnergyMeV = 7.5;


// 	// b9_a5Li_hypothesis.name = "B10ha_5LiHypothesis";
// 	// b9_a5Li_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("B",10);
// 	// b9_a5Li_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
// 	// b9_a5Li_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
// 	// b9_a5Li_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("B",9);
// 	// b9_a5Li_hypothesis.mass_intermediate = fMassTable.GetNuclearMassMeV("Li",5);
// 	// b9_a5Li_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("He",4);
// 	// b9_a5Li_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("H",1);
// 	// b9_a5Li_hypothesis.masses[2] = fMassTable.GetNuclearMassMeV("He",4);


// 	InvMass_Mult3 b9_p8Be_analysis;//, b9_a5Li_analysis;

// 	b9_p8Be_analysis.Init(p8Be_output_filename);
// 	b9_p8Be_analysis.SetHypothesis(b9_p8Be_hypothesis);
// 	// b9_p8Be_analysis.SetGate1(NOCHECK);
// 	// b9_p8Be_analysis.SetGate1MinMax({0,0});
// 	// b9_p8Be_analysis.SetGate2(NOCHECK);
// 	// b9_p8Be_analysis.SetGate2MinMax({0,0});
// 	// b9_p8Be_analysis.SetGate3(NOCHECK);
// 	// b9_p8Be_analysis.SetGate3MinMax({0,0});
// 	CutHandler& cuthandler = b9_p8Be_analysis.GetCutHandler();
// 	if(!cuthandler.LoadCutsFromConfig(cutlist_p8Be_filename)){
// 		std::cerr << "Warning: could not load at least one cut from " << cutlist_p8Be_filename << "!\n";
// 	}

// 	//test by printing cuts here:
// 	cuthandler.PrintCuts();

// 	// b9_a5Li_analysis.Init(a5Li_output_filename);
// 	// b9_a5Li_analysis.SetHypothesis(b9_a5Li_hypothesis);
// 	// b9_a5Li_analysis.SetGate1(NOCHECK);
// 	// b9_a5Li_analysis.SetGate1MinMax({0,0});
// 	// b9_a5Li_analysis.SetGate2(NOCHECK);
// 	// b9_a5Li_analysis.SetGate2MinMax({0,0});
// 	// b9_a5Li_analysis.SetGate3(NOCHECK);
// 	// b9_a5Li_analysis.SetGate3MinMax({0,0});
// 	//cuthandler = b9_a5Li_analysis.GetCutHandler();
// 	// if(!cuthandler.LoadCutsFromConfig(cutlist_a5Li_filename)){
// 	// 	std::cerr << "Warning: could not load at least one cut from " << cutlist_a5Li_filename << "!\n";
// 	// }

// 	// //test by printing cuts here:
// 	// cuthandler.PrintCuts();

// 	double Ex, SPSE, SPSTheta, SPSPhi;
// 	intree->SetBranchAddress("ExE", &Ex);
// 	intree->SetBranchAddress("SPSEnergy", &SPSE);
// 	intree->SetBranchAddress("SPSTheta", &SPSTheta);
// 	intree->SetBranchAddress("SPSPhi", &SPSPhi);

// 	double E[3], theta[3], phi[3];
// 	intree->SetBranchAddress("SabreRingEnergy_hit1", &E[0]);
// 	intree->SetBranchAddress("thetalab_hit1", &theta[0]);
// 	intree->SetBranchAddress("philab_hit1", &phi[0]);

// 	intree->SetBranchAddress("SabreRingEnergy_hit2", &E[1]);
// 	intree->SetBranchAddress("thetalab_hit2", &theta[1]);
// 	intree->SetBranchAddress("philab_hit2", &phi[1]);

// 	intree->SetBranchAddress("SabreRingEnergy_hit3", &E[2]);
// 	intree->SetBranchAddress("thetalab_hit3", &theta[2]);
// 	intree->SetBranchAddress("philab_hit3", &phi[2]);

// 	std::cout << "Starting analysis on " << numentries << " entries..." << std::endl;
// 	for(long i=0; i<numentries; i++){

// 		intree->GetEntry(i);

// 		if(updateRecoilEx){
// 			b9_p8Be_analysis.SetRecoilEx(Ex);
// 			//b9_a5Li_analysis.SetRecoilEx(Ex);
// 		}


// 		b9_p8Be_analysis.AnalyzeEvent(E, theta, phi, SPSE, SPSTheta, SPSPhi, Ex, updateIntermediateEx);
// 		b9_p8Be_analysis.FillEventHistograms(Ex);
// 		int numpasses_p8Be = b9_p8Be_analysis.CountPermPasses();
// 		b9_p8Be_analysis.FillPermCounter();
// 		b9_p8Be_analysis.FillSortedHisto(Ex);
// 		b9_p8Be_analysis.FillSABRESumEVsSPS_Ex(Ex, E[0]+E[1]+E[2]);
// 		b9_p8Be_analysis.FillTree();

// 		// b9_a5Li_analysis.AnalyzeEvent(E, theta, phi, SPSE, SPSTheta, SPSPhi, Ex, updateIntermediateEx);
// 		// b9_a5Li_analysis.FillEventHistograms(Ex);
// 		// int numpasses_a5Li = b9_a5Li_analysis.CountPermPasses();
// 		// b9_a5Li_analysis.FillPermCounter();


// 		if(i % 1000 == 0){
// 			fprintf(stdout, "\rProgress: %.1f%% (%ld/%ld)",(float)i/numentries*100., i, numentries);
// 			fflush(stdout);
// 		}

// 	}

// 	b9_p8Be_analysis.CloseAndWrite();
// 	//b9_a5Li_analysis.CloseAndWrite();

// 	infile->Close();

// 	std::cout << "\n\nAnalysis complete!\n" << std::endl;
// 	std::cout << "b9_p8Be output: " << p8Be_output_filename << std::endl;
// 	//std::cout << "b9_a5Li output: " << a5Li_output_filename << std::endl;
// }
