/*

	This code will perform invariant mass analysis on experimental and simulated data with SABRE multiplicity 3

	This code can take experimental data input in the form of the ROOT files generated by RMSRecon/etc/Rachel2Root.cxx
	which simply "ROOT"-ifies the txt files from Rachel Shaffer's sorts (see her thesis here: https://repository.lsu.edu/gradschool_dissertations/6662/)

	This code can also take simulated data output from SABREslicer.cxx located at SABREsim/det/SABREslicer.cxx. This takes SABREsim data and formats
	it in the same format as the Rachel2Root data. 


	NOTE: This code assumes that TMassTable is loaded into ROOT. This can be done by doing one of the following:

		i)		manually running '.L /path/to/masstable.cpp+' everytime you open root

													OR

		ii) 	creating/editing ~/rootlogon.C to include: 'gROOT->ProcessLine(".L /path/to/masstable.cpp+");'
				so that it runs this automatically for you. Find masstable.cpp and associated header and dat file here:
				https://github.com/zmp26/masstable

	Alternatively just remove the dependency and hardcode masses instead.

*/

#include <map>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <chrono>
#include "TFile.h"
#include "TH1D.h"
#include "TString.h"
#include "TDirectory.h"
#include "invmass_mult2.h"
#include "invmass_mult2.cpp"//including .cpp for simple root macro purposes - when writing separately compiled code, only include .h
#include "permHisto_mult2.h"//" above "
#include "permHisto_mult2.cpp"//" above "

const double DEGRAD = M_PI/180.;
const double RADDEG = 180./M_PI;

void Li7ha_adHypothesis_kin3mcComparison(const char* input_filename, int gate1index, std::pair<double,double> gate1minmax, int gate2index, std::pair<double,double> gate2minmax, bool updateRecoilEx=true){

	std::string s = input_filename;
	size_t last_dot = s.find_last_of(".");
	std::string stem = (last_dot == std::string::npos) ? s : s.substr(0, last_dot);

	std::string sabre_str = stem + "_SABREanalyzed_ad.root";
	std::string kin3mc_str = stem + "_kin3mcanalyzed_ad.root";

	const char* SABRE_output_filename = sabre_str.c_str();
	const char* kin3mc_output_filename = kin3mc_str.c_str();

	TMassTable fMassTable;
	fMassTable.Init("../config/masstable.dat");

	Hypothesis3 li7_ad_hypothesis;
	li7_ad_hypothesis.name = "Li7ha_adHypothesis";

	li7_ad_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("Li",7);
	li7_ad_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
	li7_ad_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
	li7_ad_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("Li",6);
	li7_ad_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("He",4);
	li7_ad_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("H", 2);

	TFile *infile = new TFile(input_filename, "READ");
	if(!infile || infile->IsZombie()){
		std::cerr << "Input file is bad: " << input_filename << std::endl;
		return;
	}

	TTree *intree = (TTree*)infile->Get("mult2");
	if(!intree){
		std::cerr << "Could not get TTree 'mult2' from " << input_filename << std::endl;
		return;
	}

	long numentries = intree->GetEntries();

	InvMass_Mult2 SABRE_analysis;
	SABRE_analysis.Init(SABRE_output_filename);
	SABRE_analysis.SetHypothesis(li7_ad_hypothesis);
	SABRE_analysis.SetGate1(gate1index);
	SABRE_analysis.SetGate1MinMax(gate1minmax);
	SABRE_analysis.SetGate2(gate2index);
	SABRE_analysis.SetGate2MinMax(gate2minmax);

	InvMass_Mult2 kin3mc_analysis;
	kin3mc_analysis.Init(kin3mc_output_filename);
	kin3mc_analysis.SetHypothesis(li7_ad_hypothesis);
	kin3mc_analysis.SetGate1(gate1index);
	kin3mc_analysis.SetGate1MinMax(gate1minmax);
	kin3mc_analysis.SetGate2(gate2index);
	kin3mc_analysis.SetGate2MinMax(gate2minmax);

	double kinmc_e[4], kinmc_theta[4], kinmc_phi[4];
	intree->SetBranchAddress("kin_e", kinmc_e);
	intree->SetBranchAddress("kin_theta", kinmc_theta);
	intree->SetBranchAddress("kin_phi", kinmc_phi);

	double Ex, SPSE;
	intree->SetBranchAddress("ExE", &Ex);
	intree->SetBranchAddress("SPSEnergy", &SPSE);

	double E[2], theta[2], phi[2];
	intree->SetBranchAddress("SabreRingEnergy_hit1", &E[0]);
	intree->SetBranchAddress("thetalab_hit1", &theta[0]);
	intree->SetBranchAddress("philab_hit1", &phi[0]);

	intree->SetBranchAddress("SabreRingEnergy_hit2", &E[1]);
	intree->SetBranchAddress("thetalab_hit2", &theta[1]);
	intree->SetBranchAddress("philab_hit2", &phi[1]);

	std::cout << "Starting analysis on " << numentries << " entries..." << std::endl;
	for(long i=0; i<numentries; i++){

		intree->GetEntry(i);

		double kinmc_bue[2], kinmc_butheta[2], kinmc_buphi[2];
		for(int j=0; j<2; j++){
			kinmc_bue[j] = kinmc_e[j+2];
			kinmc_butheta[j] = kinmc_theta[j+2];
			kinmc_buphi[j] = kinmc_phi[j+2];
		}

		if(updateRecoilEx){
			SABRE_analysis.SetRecoilEx(Ex);
			kin3mc_analysis.SetRecoilEx(Ex);
		}

		SABRE_analysis.AnalyzeEvent(E, theta, phi);
		SABRE_analysis.FillEventHistograms(Ex);
		int numpasses_sabre = SABRE_analysis.CountPermPasses();
		SABRE_analysis.FillPermCounter();
		SABRE_analysis.FillSortedHisto(Ex);
		if(numpasses_sabre == 1){
			SABRE_analysis.FillGatedEventHistograms(Ex);
			SABRE_analysis.FillPermCounter(true);
		}
		SABRE_analysis.FillTree();

		kin3mc_analysis.AnalyzeEvent(kinmc_bue, kinmc_butheta, kinmc_buphi);
		kin3mc_analysis.FillEventHistograms(Ex);
		int numpasses_kin3mc = kin3mc_analysis.CountPermPasses();
		kin3mc_analysis.FillPermCounter();
		kin3mc_analysis.FillSortedHisto(Ex);
		if(numpasses_kin3mc == 1){
			kin3mc_analysis.FillGatedEventHistograms(Ex);
			kin3mc_analysis.FillPermCounter(true);
		}
		kin3mc_analysis.FillTree();

		if(i%1000 == 0){
			fprintf(stdout, "\rProgress: %.1f%% (%ld/%ld)", (float)i/numentries*100., i, numentries);
			fflush(stdout);
		}

	}

	SABRE_analysis.CloseAndWrite();
	kin3mc_analysis.CloseAndWrite();
	infile->Close();

	std::cout << "\n\nAnalysis complete!\n" << std::endl;
	std::cout << "SABRE output: " << SABRE_output_filename << std::endl;
	std::cout << "kin3mc output: " << kin3mc_output_filename << std::endl;

}

void Li7ha_2par_exp_allEx(const char* input_filename, bool updateRecoilEx=true){

	std::string s = input_filename;
	size_t last_dot = s.find_last_of(".");
	std::string stem = (last_dot == std::string::npos) ? s : s.substr(0, last_dot);

	std::string ad_str = stem + "_allExAnalyzed_ad.root";

	const char* ad_output_filename = ad_str.c_str();

	TFile *infile = new TFile(input_filename, "READ");
	if(!infile || infile->IsZombie()){
		std::cerr << "Input file is bad: " << input_filename << std::endl;
		return;
	}

	TTree *intree = (TTree*)infile->Get("T");
	if(!intree){
		std::cerr << "Could not get TTree 'T' from " << input_filename << std::endl;
		return;
	}

	long numentries = intree->GetEntries();

	TMassTable fMassTable;
	fMassTable.Init("../config/masstable.dat");

	Hypothesis3 li7_ad_hypothesis;
	li7_ad_hypothesis.name = "Li7ha_adHypothesis";

	li7_ad_hypothesis.mass_target = fMassTable.GetNuclearMassMeV("Li",7);
	li7_ad_hypothesis.mass_beam = fMassTable.GetNuclearMassMeV("He",3);
	li7_ad_hypothesis.mass_ejectile = fMassTable.GetNuclearMassMeV("He",4);
	li7_ad_hypothesis.mass_recoil = fMassTable.GetNuclearMassMeV("Li",6);
	li7_ad_hypothesis.masses[0] = fMassTable.GetNuclearMassMeV("He",4);
	li7_ad_hypothesis.masses[1] = fMassTable.GetNuclearMassMeV("H", 2);

	InvMass_Mult2 li7ha_ad_analysis;

	li7ha_ad_analysis.Init(ad_output_filename);
	li7ha_ad_analysis.SetHypothesis(li7_ad_hypothesis);
	li7ha_ad_analysis.SetGate1(NOCHECK_M2);
	li7ha_ad_analysis.SetGate1MinMax({0,0});
	li7ha_ad_analysis.SetGate2(NOCHECK_M2);
	li7ha_ad_analysis.SetGate2MinMax({0,0});

	double Ex, SPSE;
	intree->SetBranchAddress("ExE", &Ex);
	intree->SetBranchAddress("SPSEnergy", &SPSE);

	double E[2], theta[2], phi[2];
	intree->SetBranchAddress("SabreRingEnergy_hit1", &E[0]);
	intree->SetBranchAddress("thetalab_hit1", &theta[0]);
	intree->SetBranchAddress("philab_hit1", &phi[0]);

	intree->SetBranchAddress("SabreRingEnergy_hit2", &E[1]);
	intree->SetBranchAddress("thetalab_hit2", &theta[1]);
	intree->SetBranchAddress("philab_hit2", &phi[1]);

	std::cout << "Starting analysis on " << numentries << " entries..." << std::endl;
	for(long i=0; i<numentries; i++){

		intree->GetEntry(i);

		if(updateRecoilEx){
			li7ha_ad_analysis.SetRecoilEx(Ex);
		}

		li7ha_ad_analysis.AnalyzeEvent(E, theta, phi);
		li7ha_ad_analysis.FillEventHistograms(Ex);
		int numpasses_ad = li7ha_ad_analysis.CountPermPasses();
		li7ha_ad_analysis.FillPermCounter();
		li7ha_ad_analysis.FillSortedHisto(Ex);
		li7ha_ad_analysis.FillTree();

		if(i%1000 == 0){
			fprintf(stdout, "\rProgress: %.1f%% (%ld/%ld)", (float)i/numentries*100., i, numentries);
			fflush(stdout);
		}

	}

	li7ha_ad_analysis.CloseAndWrite();

	infile->Close();

	std::cout << "\n\nAnalysis complete!\n" << std::endl;
	std::cout << "li7ha_ad output: " << ad_output_filename << std::endl;

}