[General]
detmc_version = 4
infile = kinmc/kin4mc/b10ha_7.5MeV_9B_ex2345keV_a5Li_ex0keV_100k.out
detfile = det/kin4mc/b10ha_7.5MeV_9B_ex2345keV_a5Li_ex0keV_100k.det
treefile = det/kin4mc/b10ha_7.5MeV_9B_ex2345keV_a5Li_ex0keV_100k_tree.root
histofile = det/kin4mc/b10ha_7.5MeV_9B_ex2345keV_a5Li_ex0keV_100k_histos.root

[Kinematics]
beam = 3 He
target = 10 B
recoil = 9 B
ejectile = 4 He
beam_energy = 7.5
recoil_excitation_energy = 2.345

[TargetLosses]
targetLoss_par1 = none
targetLoss_par2 = none
targetLoss_par3 = none
targetLoss_par4 = none

[TargetAngularStraggling]
enableStraggle1 = false
enableStraggle2 = false
enableStraggle3 = false
enableStraggle4 = false

[DeadLayerLosses]
deadLayerLoss_par1 = none
deadLayerLoss_par2 = none
deadLayerLoss_par3 = none
deadLayerLoss_par4 = none

[Beamspot]
profile = gaussian
parX = 0.0005
parY = 0.0005
beam_offsetX = 0
beam_offsetY = 0

[SPS]
 Coincidence = true
ThetaMin = 18.27
ThetaMax = 21.73
PhiMin = -2.19
PhiMax = 2.19
SigmaE = 0.015
SigmaTheta = 0.5
SigmaPhi = 0.5
ApertureDist = 0.175
